### ISSUE TITLE
Line Tax Version: AR-- and AP--Add Transaction TAB jumps

### ISSUE THREAD

**Issue by sweitmann** [ledger123/runmyaccounts#1]
In 'AR--Add Transaction' + 'Add Credit Note' and 'AP--Add Transaction' + 'Add Debit Note', when pressing the TAB key the cursor jumps as follows:
Amount > Account > Description > Tax > Project > Tax amount
instead of:
Amount > Account > Tax > Tax amount > Description > Project  

![bildschirmfoto 2015-08-27 um 15 51 07](https://cloud.githubusercontent.com/assets/100664/9522196/a87a2e0c-4cd3-11e5-99cc-4cc265be2480.png)

**Comment by ledger123** [comment]
This is fixed and code pushed.

Regards

**Comment by sweitmann** [comment]
Can't find the code pushed. Am I looking in the wrong place?

https://github.com/ledger123/runmyaccounts/commits/develop

Regards,
Sebastian

**Comment by ledger123** [comment]
My mistake. It was not pushed due to some work by Nils on this branch. Should be there now.

**Comment by sweitmann** [comment]
Perfect, thanks. Issue solved. Closing this ticket now.
