### ISSUE TITLE
Fix for rounding issue for fx ar/ap transactions

### ISSUE THREAD

**Issue by sweitmann** [ledger123/runmyaccounts#100]
THIS PART HAS BEEN SOLVED: The issue explained here was caused due to "Tax Included" box being checked when booking only tax. 

<--!

Hi Armaghan,

This fix (https://github.com/ledger123/runmyaccounts/commit/e561c4803f5ab8496271df817d61a7965ba0884e) causes an error in transactions which only contain tax account bookings.

Here is an example:
![bildschirmfoto 2016-12-23 um 13 49 34](https://cloud.githubusercontent.com/assets/100664/21454236/17620b4e-c917-11e6-8212-c7ffab517613.png)

If you load the last version / commit before the fix mentioned above (which is this one: https://github.com/ledger123/runmyaccounts/commit/62c619251c44ba3d03a9d506b13271a514b60966) and book the transaction above, then the booking is ok and thus the result looks like this:
![bildschirmfoto 2016-12-23 um 13 49 24](https://cloud.githubusercontent.com/assets/100664/21454283/7a692a10-c917-11e6-9baf-c1abe3fe687d.png)

And if you book the same transaction after the fix mentioned above, then the result looks like this:
![bildschirmfoto 2016-12-23 um 13 57 34](https://cloud.githubusercontent.com/assets/100664/21454320/cf5f09c2-c917-11e6-829f-5258bdf530a9.png)

As you can see account 2000 (summary account for AP) is then booked twice in credit and for some reason the counter account is 6952 (foreign exchange gain account). 

Regards

-->

**Comment by sweitmann** [comment]
Hi Armaghan, 

I just had a quick look at the code and think that this is the same code that always books rounding difference on foreign exchange gain account, even if it's actually a foreign exchange (rounding) loss.
I have reproduced this in AR-063 on munshi10 server.

So once we get down to fixing the issue mentioned here above, we might as well also add 
{fxloss_accno_id} option for foreign exchange losses.  

Regards

**Comment by sweitmann** [comment]
Hi Armaghan, 

This same piece of code involved the rounding issue that we discussed over Slack yesterday. Just posting it here too, so that we have all information in one place. We need to add a check here, because if you are posting a AR Credit Note or AP booking, it should not be -1, but simply 1. 

![bildschirmfoto 2017-03-28 um 17 36 54](https://cloud.githubusercontent.com/assets/100664/24445414/14c47202-146a-11e7-9fab-c47216b5925b.png)

And once we have solved this issue, do you think we can add a feature to LedgerDoctor which finds the bookings that need to be re-posted due to rounding difference caused by code above and links them, so that it’s easy for users to identify and correct the transaction?

Regards

**Comment by ledger123** [comment]
Hi Sebastian,

I could not figure out a single query to find transactions with both gain and loss accounts. But following queries when run in sequence will do that:

  DROP TABLE tmp;
  DROP TABLE tmp2;

  CREATE TABLE tmp AS SELECT DISTINCT trans_id FROM acc_trans WHERE chart_id IN (SELECT fldvalue::integer FROM defaults WHERE fldname='fxgain_accno_id');

  CREATE TABLE tmp2 AS SELECT trans_id FROM tmp WHERE trans_id IN (SELECT DISTINCT trans_id FROM acc_trans WHERE chart_id IN (SELECT fldvalue::integer FROM defaults WHERE fldname='fxloss_accno_id'));

  SELECT invnumber FROM ar WHERE id IN (SELECT trans_id FROM tmp2);
  SELECT invnumber FROM ap WHERE id IN (SELECT trans_id FROM tmp2);

Regards
