### ISSUE TITLE
Displayed tax not correct when transaction is re-opened

### ISSUE THREAD

**Issue by sweitmann** [ledger123/runmyaccounts#101]
Hi Armaghan,

Not only search engines, but also tax authorities tend to always want to collect more and more data about citizens and businesses.

Hence in some accounting transactions we need to book both positive and negative tax amounts and although these tax amounts in the end mostly add up to zero, we still need to book them accordingly to accumulate certain defined turnover in the tax report.

Here is an example of how such a booking might look:
![bildschirmfoto 2017-01-13 um 10 00 04](https://cloud.githubusercontent.com/assets/100664/21923965/2435c930-d977-11e6-8c34-890801675ec9.png)
I have booked this transaction as invoice number 221 on munshi10 for your further review.

When you look at this transaction in the Journal, everything looks fine:

![bildschirmfoto 2017-01-13 um 09 51 20](https://cloud.githubusercontent.com/assets/100664/21923702/de7be678-d975-11e6-9d7b-e3d414f0d762.png)

But when you re-open it, the tax amount in one row changes and is not displayed correctly:

![bildschirmfoto 2017-01-13 um 09 53 44](https://cloud.githubusercontent.com/assets/100664/21923771/3ac2dc70-d976-11e6-96d3-76e39adaf502.png)

This is very dangerous, because if you re-post such a transaction, the total tax amounts will change and the tax report becomes incorrect.

I would be very grateful if you could help me sort this out.

Regards

**Comment by ledger123** [comment]
Hi Sebastian,

Fix has been pushed in 101_ branch.

Regards
