### ISSUE TITLE
Project name in Income Statement

### ISSUE THREAD

**Issue by sweitmann** [ledger123/runmyaccounts#109]
Hi Armaghan, 

I have just noticed that the project name doesn't show up in the income statement. There doesn't seem to be any variable for this information, like <%project%>.

Would it be very tricky to add such a variable to the income statement?

Regards

**Comment by ledger123** [comment]
Hi Sebastian,

I just figured out from code that you can use <%projectnumber%> variable for this purpose. Please let me know if this is good enough or some adjustment is still needed.

Regards
