### ISSUE TITLE
Line Tax version: 'Include Exchange Rate Difference' in Trial Balance

### ISSUE THREAD

**Issue by sweitmann** [ledger123/runmyaccounts#11]
Hi Armaghan,

I thought we had already implemented this in the RMA Line Tax version (develop branch), but couldn't find it, so I checked out the Rel3 develop branch instead and found it there. 

Could you please add this feature to the RMA Line Tax version and also launch it in the standard Rel3 branch? 

![bildschirmfoto 2015-09-09 um 17 15 46](https://cloud.githubusercontent.com/assets/100664/9765948/ed39d432-5716-11e5-874e-257113ec40f3.png)

Regards
Sebastian

**Comment by ledger123** [comment]
Hi Sebastian,

This is done and pushed to github. Kindly have a look and let me know if you find any issue.

Regards

**Comment by sweitmann** [comment]
Hi Armaghan,

looking good, but it all depends on how I have set my preferences. 

For example when I open this booking:

![bildschirmfoto 2015-09-17 um 16 55 15](https://cloud.githubusercontent.com/assets/100664/9936635/35fe2b40-5d5d-11e5-94d3-a70415f72b3d.png)

With my number preferences set to 1'000.00, it looks like this:

![bildschirmfoto 2015-09-17 um 16 56 28](https://cloud.githubusercontent.com/assets/100664/9936656/505e59ba-5d5d-11e5-9f85-19c1e303abd8.png)

But if I change my preferences to 1.000,00 (as the standard used in Germany), I get wrong numbers:

![bildschirmfoto 2015-09-17 um 16 55 33](https://cloud.githubusercontent.com/assets/100664/9936675/6d6da7ea-5d5d-11e5-883a-141d796077d3.png)

Regards

**Comment by ledger123** [comment]
Hi Sebastian,

This has been fixed and pushed to github. This bug was due to calling update function BEFORE displaying the form.

Regards

**Comment by sweitmann** [comment]
Tested. Solved. Thanks Armaghan! Closing this ticket now.
