### ISSUE TITLE
Add currency and exchange rate checkbox to journal

### ISSUE THREAD

**Issue by sweitmann** [ledger123/runmyaccounts#110]
Hi Armaghan,

would it be possible to add a currency and exchange rate checkbox in the journal? 

Regards

**Comment by ledger123** [comment]
Hi Sebastian,

I have added currency and exchange rate checkboxes in the journal report in 110 branch. Kindly check and confirm the accuracy.

Do we need to add these to the CSV export too?

Regards

**Comment by sweitmann** [comment]
Hi Armaghan, 

Looks great! Could you just adjust, so that the exchange rate is not rounded? Currently 0.89202516 shows up as 0.90 in the journal.

Regards

**Comment by sweitmann** [comment]
Released into develop. Thanks, Armaghan! Closing this ticket now.

**Comment by sweitmann** [comment]
Hi Armaghan,
When you post a foreign currency AR or AP transaction with payment at a different date than the transaction itself, you might have different exchange rates in one transaction.

![Screenshot 0](https://user-images.githubusercontent.com/100664/54117989-52189480-43f2-11e9-956b-8bc4cbaedd00.png)

If you list such a transaction in the journal view only one exchange rate is shown. 

![Screenshot 2](https://user-images.githubusercontent.com/100664/54118073-7bd1bb80-43f2-11e9-83ff-35682b1cc975.png)

Is there a way to have both exchange rates shown?

Regards

**Comment by sweitmann** [comment]
Hi Armaghan, 

Tested and as far as I can see, it still only shows the exchange rate for main booking, not also for payment. 

Can you please re-check the code?

Regards

**Comment by sweitmann** [comment]
Wonderful, thanks Armaghan! Closing this ticket now.
