### ISSUE TITLE
Reminders PDF-File Name needs unique part containing to dataset

### ISSUE THREAD

**Issue by sweitmann** [ledger123/runmyaccounts#115]
Hi Armaghan,

as discussed earlier today, we need to change the code that creates the file name for reminders, so that they become unique for each dataset.

Regards
Sebastian

**Comment by ledger123** [comment]
Hi Sebastian,

Do you mean the name for the file which is generated when we click 'Create Single PDF' and print to queue?

This single pdf is already prefixed with complete username (username@dbname) as shown in the screen shot below so it always unique for each dataset if you are using usernames in this format.

Can you please confirm if I am not interpreting the issue correctly?

Regards

![Selection_053](https://user-images.githubusercontent.com/13597/143552577-8d8487ab-3b0e-4832-a4ac-f6bfdd0e7d6d.png)

**Comment by ledger123** [comment]
Hi Sebastian,

This is done as shown in the screen shot. Now @phkroll  can merge it.

Regards

![Selection_032](https://user-images.githubusercontent.com/13597/159890603-b15f9b2e-b096-44c8-889d-23a1e5deb082.png)

**Comment by phkroll** [comment]
merged to develop
