### ISSUE TITLE
Backup / Restore Issue

### ISSUE THREAD

**Issue by sweitmann** [ledger123/runmyaccounts#117]
Hi Armaghan,

We need to add new database columns to Pg-tables.sql, so that Backup / Restore works without issues. 

Regards

**Comment by ledger123** [comment]
I could not figure out the issue from code. Will need backup file to test.

But I have modified the backup script to use pg_dump. This creates very small backup files quickly which also take very little time to restored compared to the old built-in method.

Code is pushed in 117_backup_restore_issue branch for your testing and also updated on munshi10.net

Regards

**Comment by sweitmann** [comment]
Hi Armaghan, this new backup feature works beautifully now. Also the new template backup feature is very handy. 

What do you think about now also adding a restore feature to restore pg_dump backup file templates.tar backup?

Regards

**Comment by sweitmann** [comment]
Thanks, Armaghan! :)
