### ISSUE TITLE
Clearing Account feature

### ISSUE THREAD

**Issue by sweitmann** [ledger123/runmyaccounts#119]
Hi Armaghan,

here some small issues that need to be fixed with the Clearing Account feature.

a.) Partial payments
Currently this is not working correctly. It would be great if we could fix this, so that one can do partial payments. If we have one payment of 388,56 on the clearing account and two open invoices of 129,52, it would be great if it were possible to close the two invoices of 129,52 and have the rest remain on the clearing account. 

![a1](https://user-images.githubusercontent.com/100664/39803487-720d793a-5371-11e8-9e01-72a2f202c825.png)

b.) Sorting by column
When clicking on the date of one of the transactions on the clearing account, I get a list of the open AR/AP transactions listed below. It would be great if one could sort these in different ways simply by clicking on the header of each column. If, for example, I see that the transaction is related to a certain customer or vendor, I will want to sort the listed transactions by "Name". 

![b1](https://user-images.githubusercontent.com/100664/39803506-7d7d286a-5371-11e8-9060-61f727bce691.png)

Regards
Sebastian

**Comment by sweitmann** [comment]
Hi Armaghan, 

When I book partial payment and after that then book rest an close transaction, the selected account remains visible but without amounts if I open that transaction.

<img width="833" alt="bildschirmfoto 2018-05-10 um 15 06 24" src="https://user-images.githubusercontent.com/100664/40097356-01b9eb72-58d6-11e8-9e5d-a6f7818a2725.png">

Regards

**Comment by sweitmann** [comment]
Hi Armaghan,

If the amount on selected account is < total amount of AP/AR transaction, only the amount on selected account should be booked as payment. Currently it books total amount of AP/AR transaction and debits/credits rest on selected account.

Regards

**Comment by sweitmann** [comment]
Hi Armaghan,
Next thing that has already been requested it that clearing account feature also matches foreign currency transactions. In Switzerland they very often have customers with EUR bank accounts and EUR transactions. Since the currency in Switzerland is CHF, in the Swiss sql-ledger databases EUR is considered a foreign currency. Currently our clearing account feature only matches amounts on clearing account with open AR or AP transactions if they are both in the databases national currency. If they are both in a foreign currency instead the clearing account feature doesn't match them. 
Any idea how we could solve this?
Regards

**Comment by sweitmann** [comment]
<img width="1189" alt="bildschirmfoto 2018-09-20 um 08 52 11" src="https://user-images.githubusercontent.com/100664/45800954-bfa0ff00-bcb2-11e8-9770-303dd8f728c1.png">

**Comment by sweitmann** [comment]
Hi Armaghan, this commit (https://github.com/ledger123/runmyaccounts/commit/e68eba1a3b4a94dab6bf2e358333ac25da48c584) contains a bug. After this commit payment of AR invoices that are booked with Selected Account feature go in the wrong direction:

![bildschirmfoto 2018-10-01 um 09 56 42](https://user-images.githubusercontent.com/100664/46277959-24870f80-c565-11e8-9153-0ea2e7e74379.png)

Regards

**Comment by ledger123** [comment]
Hi Sebastian,

Pushed an update. I tried to test all possibilities but getting confused with few things. Please test and let me know if there is still problem.

Regards

**Comment by sweitmann** [comment]
Perfect, thanks Armaghan! Transaction open link on just-do-it screen works beautifully now. 

A colleague has requested that we also add customer / vendor to just-do-it screen: 

![bildschirmfoto 2018-10-11 um 14 09 26](https://user-images.githubusercontent.com/100664/46803014-59fadc80-cd5f-11e8-8a4b-343cf5ead8c3.png)

Regards

**Comment by sweitmann** [comment]
Hi Armaghan, thank you once again for your fantastic work. As discussed on Slack here are some small cosmetic issues. 

Currently, the "Include Exchange Rate Difference" checkbox is marked by default:

<img width="987" alt="bildschirmfoto 2018-12-10 um 11 17 20" src="https://user-images.githubusercontent.com/100664/49725963-3673e580-fc6d-11e8-87ef-8fe8f029a42d.png">


Please leave "Include Exchange Rate Difference" unchecked by default. Since you show a column stating the transaction currency, we can skip the exchange rate difference by default in the mentioned checkbox. 

Regards

**Comment by sweitmann** [comment]
Hi Armaghan, 

I love this new fx feature. Please release into develop.

Regards
