### ISSUE TITLE
Hotfix2: Add project name variable for sales invoice template

### ISSUE THREAD

**Issue by sweitmann** [ledger123/runmyaccounts#12]
Hi Armaghan,

always nice talking to you. As discussed on the phone, it would be really great if you could help add a "project name" variable for the sales invoice template.

Regards
Sebastian

**Comment by ledger123** [comment]
Hi Sebastian,

Added 'projectname' variable. This update is available in hotfix2 branch.

Regards

**Comment by sweitmann** [comment]
Hi Armaghan,

thanks a million. Just tested it, but for some reason instead of the project name and project number, I get:

ARRAY(0x29331c0A)RRAY(0x31e1238R)

![bildschirmfoto 2015-09-16 um 13 39 07](https://cloud.githubusercontent.com/assets/100664/9903680/8b78b170-5c78-11e5-85f8-9772f8fb9826.png)

Any ideas of what I might be doing wrong?

Regards
Sebastian

**Comment by ledger123** [comment]
Hi Sebastian,

It is working fine at my end as you can see from screen shot. 

This is a loop variable which means that you need to put it  <%foreach number%>. Are you doing just like that?

Regards
![project](https://cloud.githubusercontent.com/assets/13597/9904311/232bade8-5c96-11e5-80d7-2d10bb7ead32.png)

**Comment by sweitmann** [comment]
Hi Armaghan,

I'm very sorry, you are absolutely right; it works fine! My mistake. 

Until today, I didn't know the word "loop variable" :) That was exactly the thing I was doing wrong: I was using a loop variable without <%foreach number%>.

Closing this ticket now. Thanks again, Armaghan.
