### ISSUE TITLE
Number format issue - 312,55 becomes 31.255,00

### ISSUE THREAD

**Issue by sweitmann** [ledger123/runmyaccounts#121]
Hi Armaghan, 

This issue is related to the German number format (1.000,00) and to our recent fix for searching with this number format in the journal. 

If I search for the amount 312,55 in 'General Ledger--Reports--Journal' initially the related transactions are both found:

![bildschirmfoto 2018-05-17 um 08 00 42](https://user-images.githubusercontent.com/100664/40159206-700a193a-59a8-11e8-8112-72d3c88c46ce.png)

If I then open one of the transactions, make an adjustment and re-post it, the number 312,55 changes to 31.255,00 and thus the searched transactions are no longer listed:

![bildschirmfoto 2018-05-17 um 08 00 09](https://user-images.githubusercontent.com/100664/40159211-766b3052-59a8-11e8-8744-d2d3d42bd6d7.png)

It would be great if you could look into this at your convenience. 

Regards

**Comment by ledger123** [comment]
Hi Sebastian, 

This is fixed and pushed in 121_number_format_issue_in_gl branch.

Regards

**Comment by sweitmann** [comment]
Hi Armaghan,

Thanks. Tested. Works beautifully now. 

Please release into develop.

Regards

**Comment by sweitmann** [comment]
Closing this ticket. Thanks, Armaghan!
