### ISSUE TITLE
Sort AR/AP by due

### ISSUE THREAD

**Issue by sweitmann** [ledger123/runmyaccounts#123]
Hi Armaghan,

In order to be able to quickly find invoices that have been overpaid, we need to be able to sort AR and AP transactions ('AR/AP--Reports--Transactions') by 'Due'.

![bildschirmfoto 2018-06-27 um 08 09 26](https://user-images.githubusercontent.com/100664/41955714-721c2ba6-79e1-11e8-9d0d-9ce6386ea287.png)

Regards

**Comment by ledger123** [comment]
This has been added in branch 123_sort_ar_ap_by_due

Regards

**Comment by sweitmann** [comment]
Hi Armaghan, it now works beautifully, thanks. 

Regards
