### ISSUE TITLE
Ledger Doctor 'delete blank non-TAX rows' also deletes blank TAX rows

### ISSUE THREAD

**Issue by sweitmann** [ledger123/runmyaccounts#124]
Hi Armaghan,

There is no difference between the 'Click here to delete blank rows' and 'Click here to delete non-TAX rows'. Also delete TAX rows are deleted when you click on the second alternative.

The problem can also be seen on the count of rows:
![screenshot from 2018-06-29 12-14-22](https://user-images.githubusercontent.com/100664/42087291-fdebd0d6-7b95-11e8-97b9-0a36bbdd40dc.png)

As you can see it says 'There are 1804 blank rows... / There are 344 blank TAX rows... / There are 1804 blank non-TAX rows...'. 

Regards
Sebastian

**Comment by ledger123** [comment]
Hi Sebastian, 

The first button 'Click here to delete blank rows' is also meant to delete only non-tax blank rows. This means third option is just redundent and we can remove that.

But can you confirm if the first button ("Click here to delete blank rows") works correctly and deletes only non-tax blank rows?

Regards

**Comment by sweitmann** [comment]
Hi Armaghan, 

The first button 'Click here to delete blank rows' deletes all blank rows - also blank tax rows. Just tested and can confirm that. 

The second button 'Click here to delete blank TAX rows' works fine.

The third button 'Click here to delete blank non-TAX rows' also works fine. The only problem is that it does not count the amount correct. It counts the same as first button, but should only count blank non-TAX rows. 

Regards

**Comment by sweitmann** [comment]
Hi Armaghan,

The first button deletes all blank rows; TAX rows and non-TAX rows.

And the third button is the same as first, but it should only delete non-TAX rows, which it does not. It deletes all blank rows, no matter if tax or not.

Regards
