### ISSUE TITLE
Hotfix2: Print multiple reminders to queue

### ISSUE THREAD

**Issue by sweitmann** [ledger123/runmyaccounts#13]
Hi Armaghan,

it would be fantastic if we could also print multiple invoices to the queue. As it is now, they can only be printed to queue one by one.

Regards
Sebastian

**Comment by ledger123** [comment]
Hi Sebastian,

This has been fixed. While trying to add this function I noticed that code was already there but contained bugs so I had to find and fix those bugs and it took little while.

Pushed to github. Have a few tests and let me know if you find any issue.

Regards

**Comment by sweitmann** [comment]
Thanks, Armaghan! Will test and let you know if I find any issues.


Have a nice weekend.
Regards

Sebastian

**Comment by sweitmann** [comment]
Perfect. Thanks, everything works now. Closing this ticket.
