### ISSUE TITLE
VAT in recurring transactions doesn't respect number format

### ISSUE THREAD

**Issue by sweitmann** [ledger123/runmyaccounts#138]
VAT in recurring transactions doesn't respect number format

**Comment by ledger123** [comment]
Hi Sebastian,

Do you mean the the transactions generated through recurring have wrong tax amount or don't show correct amount when open or something else? Please let me know. These minor issues are minor and will be able to fix quickly after your reply.

Regards

**Comment by ledger123** [comment]
Hi Sebastian,

This is fixed and posted in 138_vat_recurring_trans_formating_issue

Regards
