### ISSUE TITLE
Line Tax version: GL transactions show empty lines

### ISSUE THREAD

**Issue by sweitmann** [ledger123/runmyaccounts#14]
Hi Armaghan,

as discussed on the phone, if you open a GL transaction you will find that it does not show the booking correctly. For some reason it shows empty lines. Any ideas?

Regards
Sebastian

**Comment by ledger123** [comment]
Hi Sebastian,

This has been fixed and pushed to 'develop' branch.

Regards

**Comment by sweitmann** [comment]
Hi Armaghan, 

you have done it agian: Solved - Thank you! Closing this ticket now.
