### ISSUE TITLE
'Batch--Email--Vendor Invoices' uses Sales Invoice instead of Vendor Invoice template

### ISSUE THREAD

**Issue by sweitmann** [ledger123/runmyaccounts#140]
Hi Armghan,

When you email an invoice using 'Batch--Email--Vendor Invoice' it is sent with the wrong template. Instead of using the correct Vendor Invoice template:
![bildschirmfoto 2019-02-08 um 16 54 39](https://user-images.githubusercontent.com/100664/52489647-0ab8a180-2bc3-11e9-8eaa-8e5dba631f70.png)

It uses the Sales Invoice template:
![bildschirmfoto 2019-02-08 um 16 57 11](https://user-images.githubusercontent.com/100664/52489664-1a37ea80-2bc3-11e9-8ce0-486502de95bb.png)

This fix is important and rather urgent for Thomas, so if it's not too tricky, it would be great if you could look into this whenever convenient. 

Regards

**Comment by ledger123** [comment]
Hi Sebastian,

This is fixed and code is pushed to github in follow branch:

140_sales_invoice_template_instead_of_vendor_invoice_in_batch_email

Regards

**Comment by sweitmann** [comment]
Hi Armaghan, 

If not already done. Please release to develop.

Closing this ticket now.

Regards
