### ISSUE TITLE
Selected account defaults

### ISSUE THREAD

**Issue by sweitmann** [ledger123/runmyaccounts#147]
Hi Armaghan, 

There are two defaults for the selected account feature to work:

a.) Selected Account and
b.) Transition Account

Apparently, if you forget to set the transition account the feature still works, but creates a mess. 

Would it be possible to check if both a.) and b.) are defined before allowing the selected account feature to be used?

Regards
Sebastian

**Comment by sweitmann** [comment]
Here is an example what the booking looks like when transition account is not set and payment is booked with Selected account Feature:

![Uploading Bildschirmfoto 2021-03-16 um 09.53.14.png…]()

**Comment by ledger123** [comment]
Hi Sebastian,

I have added lines to raise error in case if selected or transition accounts are missing in defaults.

Please test in your convenience and then I shall merge into develop.

Regards

**Comment by sweitmann** [comment]
Hi Armaghan, 

Once again: Wonderful, great solution. Thanks!

Please release to develop.

Regards
