### ISSUE TITLE
Trial Balance - 'All Accounts'

### ISSUE THREAD

**Issue by sweitmann** [ledger123/runmyaccounts#152]
Hi Armaghan, 

When I run a trial balance and also want to see the accounts which have a balance but have not been booked in the selected period, I mark the 'All Accounts' checkbox:

![Screenshot from 2019-04-26 09-30-57](https://user-images.githubusercontent.com/100664/56790986-4b10de80-6806-11e9-9ca0-1da4ae9eb1b2.png)

Currently, this results in the Trial Balance showing also accounts without any balance at all:

![Screenshot from 2019-04-26 09-34-47](https://user-images.githubusercontent.com/100664/56791218-d12d2500-6806-11e9-9d44-bb81c73832d8.png)

Would it be possible to only show accounts with a balance at the end of the selected period?

Regards

**Comment by sweitmann** [comment]
As discussed in Lahore: We might need another checkbox 'Include empty accounts'.

**Comment by ledger123** [comment]
Hi Sebastian,

Updated code with 'Empty Accounts' checkbox. Please test at your convenience.

Regards

**Comment by sweitmann** [comment]
Hi Armaghan,

Wonderful. Looks great. Thanks. 

Please release to develop. Closing this ticket now. 

Regards
