### ISSUE TITLE
Reminders batch emailing feature

### ISSUE THREAD

**Issue by sweitmann** [ledger123/runmyaccounts#154]
Hi Armaghan,

This is requested by many clients. They want to batch email reminders, just like they can batch email invoices (Tools--Batch--Email Sales Invoices).

Regards

**Comment by ledger123** [comment]
Hi Sebastian,

This functionality is added as follows:

1. Queue reminders from AR--Reports--Reminders
2. Batch email reminders using Batch--Email--Reminders

Code is available in the respective branch and commit is linked to this ticket above.

Regards

**Comment by sweitmann** [comment]
Hi Armaghan, 

Please add email and cc-email to list in Batch--Email--Reminders. 

Regards

**Comment by ledger123** [comment]
Hi Sebastian,

The discussed changes are done and you can test at your convenience.

Regards

**Comment by phkroll** [comment]
merged
