### ISSUE TITLE
DBI error in Line Tax Report

### ISSUE THREAD

**Issue by sweitmann** [ledger123/runmyaccounts#155]
Hi Armaghan,

When there aren't any bookings in a certain period and this period is selected in the Line Tax Report, the error message says:

"Error! DBI error: at bin/mozilla/reports.pl line 416."

But I think it should say:

"Error! The selected period doesn't contain any accounting data"

Do you agree? And if so, please add the more precise error message. Thanks!

Regards

**Comment by ledger123** [comment]
This is fixed and error is report is removed. Now blank report is shown as in all other built-in reports.

Pushed in develop branch.

**Comment by sweitmann** [comment]
Thanks, Armahgan! Wonderful. Closing this ticket now. 

Regards
