### ISSUE TITLE
Line Tax Report for departments

### ISSUE THREAD

**Issue by sweitmann** [ledger123/runmyaccounts#156]
Hi Armaghan,

Can we add the possibility in 'System--Line Tax Report' to run it for departments? Currently it doesn't make any difference what department I select. The result is always the same as if no department was selected. 

Regards

**Comment by ledger123** [comment]
Hi Sebastian, just added and tested this restriction in 156_department_restriction_in_line_tax_report

Regards

**Comment by sweitmann** [comment]
Hi Armaghan, nice, great work. Really appreciate this new feature. Thanks a million. Please release to develop. 

Closing this ticket now. 

Regards
