### ISSUE TITLE
Total show on screen after printing from queue not correct

### ISSUE THREAD

**Issue by sweitmann** [ledger123/runmyaccounts#157]
Hi Armaghan,

When you want to print invoices to queue using 'Tools--Batch--Print Sales Invoices' before you start the total amount for all invoices is shown in the bottom right corner:

![Bildschirmfoto 2019-08-30 um 17 28 50](https://user-images.githubusercontent.com/100664/64032893-aa338680-cb4b-11e9-9722-e5ebcd6a9de3.png)

If you then select all invoices and start printing the total shown on screen once they have all been printed is not the same:

![Bildschirmfoto 2019-08-30 um 17 37 12](https://user-images.githubusercontent.com/100664/64033476-d6033c00-cb4c-11e9-9929-7ccc6b2f40ab.png)

The reason is that after printing it sums up the totals without considering fx-amount. 

Could you please adjust this at your convenience?

Regards

**Comment by ledger123** [comment]
It is done.

**Comment by phkroll** [comment]
merged to dev.
