### ISSUE TITLE
Add Employee to 'System--Audit Trail' list

### ISSUE THREAD

**Issue by sweitmann** [ledger123/runmyaccounts#158]
Hi Armaghan,

Today the Employee is not shown in the 'System--Audit Trail' list. You can select Employee and then search his/her transactions, but we would like to add the Employee as a column in the list itself.

Regards

**Comment by ledger123** [comment]
Hi Sebastian,

This was actually a little bug. Fixed and pushed to 158_add_employee_to_audit_trail_report branch.

Regards

**Comment by sweitmann** [comment]
Hi Armaghan, 

Cool, now it works beautifully. Thanks for your excellent work. Please release to develop.

Closing this ticket now.

Regards
