### ISSUE TITLE
New Variables in Reminders

### ISSUE THREAD

**Issue by tbraendle** [ledger123/runmyaccounts#16]
To be able to print all relevant information into reminders, following bank related variables should also be available in the 3 reminder templates: 

<%dcn group=5right%>
<%rvc%>
<%dcn%>
<%bankstate%>
<%bankzipcode%>
<%bankcity%>
<%out_decimal%>
<%bankname%>
<%integer_out_amount%>
<%membernumber%>
<%bic%>
<%iban%>

**Comment by ledger123** [comment]
Hi Thomas,

I have added variables with slight name change to avoid a few conflicts and also for clarity.

            <%bankaddress1%> \\
            <%bankaddress2%> \\
            <%bankbic%> \\
            <%bankcity%> \\
            <%bankcountry%> \\
            <%bankdcn%> \\
            <%bankiban%> \\
            <%bankmembernumber%> \\
            <%bankname%> \\
            <%bankrvc%> \\
            <%bankstate%> \\
            <%bankzipcode%> \\
            <%integer_out_amount%> \\
            <%out_decimal%> \\

integer_out_amount is not formatted. It is ok or should it be formatted?

Code pushed to github in develop branch.

Regards

**Comment by ledger123** [comment]
Copied/paste from template so please ignore the new lines \\

Regards

**Comment by tbraendle** [comment]
Dear Armaghan

Thanks a lot for handling this so quick! I think it does not have to be formated - or it should be handeled the same like in the invoice.tex template.

We will test it and get back to you.

Best regards
Thomas

**Comment by ledger123** [comment]
Hi Thomas,

This fix was not working because I had added 'bankdcn' instead of 'dcn' as well as 'bankrvc' instead of 'rvc'. I have modified the online template by adding 'bank' to 'dcn' and 'rvc' and it seems to be working now. I have also printed a reminder1 and seems to be fine to me.

Also I see two >> at two places. Is this intended?

Regards

**Comment by sweitmann** [comment]
Hi Armaghan,

Can you please push this code to git (develop), so that we can test it. Thomas just tried it out on app.myledger..., but it didn't work there.

Regards
Sebastian

**Comment by tbraendle** [comment]
Dear Armaghan

Thanks a lot for your help! Sebastian and me have had a very busy day,
since we have launched Run my Accounts in the Media and were very
successful with that. The largest IT Newsticker made a story out of it:
http://www.netzwoche.ch/de-CH/News/2015/11/03/Braendle-blaest-zum-Angriff.aspx

> Also I see two >> at two places. Is this intended?

This is the adoption of the Swiss remittance voucher. We fill the
following fields:

RVC: 01<%integer_out_amount 8%><%out_decimal%><%modulo10%>
DCN: XXXXXX<%invnumber 20%><%modulo10%>

In the template we build the unique remittance voucher number as follows:

<%rvc%>><%dcn%>+ <%bankstate%>>

So betwenn the >'s should be the content.

Best regards
Thomas

Thomas Brändle | lic. oec. HSG, lic. iur HSG
Mockenwiesstrasse 37m | 8713 Uerikon | Switzerland
Tel +41 44 923 81 83 | Mobile +41 79 504 25 00
thomas@braendle.com | www.braendle.com
twitter.com/tomibraendle | facebook.com/tbraendle

Am 03.11.15 um 12:11 schrieb Armaghan Saqib:

**Comment by sweitmann** [comment]
Looks fantastic. Great work. Thanks Armaghan! Closing this ticket now.

**Comment by tbraendle** [comment]
Thanks a lot, looks great!
