### ISSUE TITLE
Variables in Reminders

### ISSUE THREAD

**Issue by sweitmann** [ledger123/runmyaccounts#160]
Hi Armaghan,

In this ticket (https://github.com/ledger123/runmyaccounts/issues/16) Thomas requested that we add some variables to the reminders feature, so that he could print all his relevant information into the 3 reminder templates. 

Now it seems these variables are not working any more. 

How shall we best proceed to sort this out? Shall we do some common testing on munshi10 in order to try to reproduce this together?

Regards

**Comment by sweitmann** [comment]
Hi Armaghan,

I have run a $self->debug; on line 672 in Form.pm and found some more details in regard to the above. When printing an AR-invoice these variables all contain the following information:

bankstate = 0101XXX588
bankzipcode = 8XX5
bankcity = OBEREMBRACH
bankcountry = CH


When printing a Reminder for the same invoice the followings variables instead don't contain any information at all:

bankstate =
bankzipcode = 
bankcity = 
bankcountry = 

Could you please check if you can find the reason for this?

**Comment by ledger123** [comment]
Hi Sebastian,

Surprisingly for me, it is printing bank information both for reminder and invoice for invoice AR-088 on munshi10

Can you please check if I am missing something?

Regards
![Screenshot from 2019-11-12 11-23-05](https://user-images.githubusercontent.com/13597/68647263-46600d80-053f-11ea-8437-c7c3a7bca041.png)
![Screenshot from 2019-11-12 11-23-30](https://user-images.githubusercontent.com/13597/68647264-46600d80-053f-11ea-9538-82df0255b72a.png)

**Comment by sweitmann** [comment]
Hi Armaghan,

Strange. On my server it looks like this:
![Bildschirmfoto 2019-11-12 um 14 22 29](https://user-images.githubusercontent.com/100664/68675541-651ece00-0558-11ea-89e3-bccf66e19f2f.png)

![Bildschirmfoto 2019-11-12 um 14 26 00](https://user-images.githubusercontent.com/100664/68675552-6a7c1880-0558-11ea-8e4e-f6dbdec56077.png)

Any ideas?

Regards

**Comment by sweitmann** [comment]
Hi Armaghan,

If you do the following in the database I sent you Wednesday, November 13th:

a.) Edit customer number 2211 and set 'Payment' to bank account 1020.
b.) Run 'AR--Reports--Transactions' and print invoice 9402 showing variables on screen.

You will see the variable: 
bankrvc = 01<%integer_out_amount 8%><%out_decimal%><%modulo10%>

This variable does not exist when you run 'AR--Reminder' for that same invoice. 

Can we add this missing variable to 'AR--Reminder'? If so, we have finally solved the problem and can close this ticket. 

Regards

**Comment by ledger123** [comment]
I have added bankrvc in reminders printing and pushed code.


Regards

**Comment by sweitmann** [comment]
Perfect, thanks Armaghan! Please release to develop.
Closing this ticket now.
Regards
