### ISSUE TITLE
Modify yearend code to do year closing by department

### ISSUE THREAD

**Issue by sweitmann** [ledger123/runmyaccounts#162]
Hi Armaghan,

As discussed please add this feature from rel3 to the runmyaccounts version:
 
https://github.com/ledger123/ledger123/commit/3d2202245090e258ebeeeaf7abd5c407d60f936e

https://github.com/ledger123/ledger123/commit/193a53865d43a22be655b9aa174e81cfaedb8bf4

https://github.com/ledger123/ledger123/commit/e694d13bdaf087bda037c05f57e7bdf6fca9d0a5

Regards

**Comment by ledger123** [comment]
Hi Sebastian,

Just ported and updated to github. Also switched munshi10 to this branch for testing.

Regards

**Comment by sweitmann** [comment]
Hi Armaghan, 

Thanks a million. This was a tricky one, but it works perfect now. Closing this ticket.

Regards
