### ISSUE TITLE
Description and Company Name in 'Cash--Reconciliation'

### ISSUE THREAD

**Issue by sweitmann** [ledger123/runmyaccounts#163]
Hi Armaghan, 

When I run the 'Cash--Reconciliation' feature the column 'Description' shows the description text for GL transactions and the company name for AP and AR transactions:

![Bildschirmfoto 2019-11-12 um 14 00 28](https://user-images.githubusercontent.com/100664/68674090-74e8e300-0555-11ea-9d5a-b42238853039.png)

Would it be possible to show the description also for AP and AR transactions instead? And if so, would it also be possible to add a checkbox to the first window with possibility to add company name column in report if needed?

![Bildschirmfoto 2019-11-12 um 14 06 38](https://user-images.githubusercontent.com/100664/68674197-b24d7080-0555-11ea-916d-1d6256abd860.png)

Regards

**Comment by ledger123** [comment]
Hi Sebastian, these can be hopefully added. I am updating today.

Regards

**Comment by ledger123** [comment]
Hi Sebastian,

This is done and pushed in 163_description_and_company_name_in_reconciliation branch.

Also updated on munshi10 for testing.

Regards

**Comment by sweitmann** [comment]
Hi Armaghan, 

Fantastic. Looks great. Thanks! Please release to develop. 

Closing this ticket now. 

Regards
