### ISSUE TITLE
Unbalanced journal due to foreign currency calculation

### ISSUE THREAD

**Issue by sweitmann** [ledger123/runmyaccounts#165]
Hi Armaghan,

Please try this on munshi10:

a.) Locate transaction PRA-001

![Bildschirmfoto 2019-12-24 um 11 33 58](https://user-images.githubusercontent.com/100664/71409311-648e5280-2641-11ea-8c19-ebeaf480c891.png)

b.) Follow the instructions defined in Notes

c.) The result is a FX-Adjustment transaction that looks as follows and which results in unbalanced journals

![Bildschirmfoto 2019-12-24 um 11 41 14](https://user-images.githubusercontent.com/100664/71409558-53921100-2642-11ea-9291-1d736f186745.png)

Can you please check the code containing calculation? I guess there must be some issue there that causes this. 

Regards

**Comment by ledger123** [comment]
Hi Sebastian,

This issue seems to be with the precision settings. I have forced precision settings to 8 for calculating during posting and it seems to be fixed. Please do your testing and let me know if this is the right way to do this.

munshi10 also updated with this change.

Regards

**Comment by sweitmann** [comment]
Hi Armaghan, 

You have done it again; Problem solved. Wonderful, thanks. 

Please release to develop.

Regards
