### ISSUE TITLE
Email bcc: kills cc:

### ISSUE THREAD

**Issue by sweitmann** [ledger123/runmyaccounts#166]
Hi Armaghan,

When we send emails from sql-ledger to customers with both cc: and bcc: emails recorded in the customer master data, only the bcc: mails are sent accordingly.

In other words, if you add a bcc: address to the core data sql-ledger will no longer send the email to whichever address you have saved in cc: 

Regards
Sebastian

**Comment by ledger123** [comment]
Hi Sebastian,

This is fixed in branch 166_bcc_kills_cc and pushed to github.

Also branch switched on munshi10

Regards
