### ISSUE TITLE
Reminder bank account by invoice not by customer settings

### ISSUE THREAD

**Issue by sweitmann** [ledger123/runmyaccounts#168]
As discussed in Lahore.

**Comment by ledger123** [comment]
Hi Sebastian,

Just went through the code for reminders in SL/RP.pm and it seems that bank account shown is already taken from the invoices table as shown in the screen shot below. Could you please reconfirm this issue? 

Also I see that all bank table columns are included in the SQL-statement so as per your second update, can you please specific which variables we cannot find there?

I shall take care of #172 issues (invoice variables, sorting) under that ticket.

Regards

![Selection_043](https://user-images.githubusercontent.com/13597/142979918-6a2a119a-91c6-4bfa-957e-3e719913cc0a.png)

**Comment by sweitmann** [comment]
Hi Armaghan, 

Thank you for looking into this. I have done some testing and this is my conclusion.

Not all bank details for the payment account in the booking are provided as variables. Bankadress 1 and 2, bankcity, bankcountry and bankzipcode are missing
![Bildschirmfoto 2021-11-23 um 16 48 52](https://user-images.githubusercontent.com/100664/143057534-b568cdfb-02b9-415e-87d9-9853fb6e4f66.png)

And also the last three bankdetails "qriban, strdbkginf and invdescriptionqr" are missing:

![Bildschirmfoto 2021-11-23 um 16 49 13](https://user-images.githubusercontent.com/100664/143057814-5a4f1d9c-d247-4fcf-b13e-ac17ef61cc38.png)

Regards

**Comment by ledger123** [comment]
Hi Sebastian,

This is correct in develop as it was a minor change. Now all variables are displayed correctly as I tested with dumper function.

Regards

![Selection_060](https://user-images.githubusercontent.com/13597/144002783-e23e5d23-5ef1-4f18-82e4-a372f28a5dad.png)

**Comment by sweitmann** [comment]
Hi Armaghan, 

Fantastic, thank you! Closing this ticket now. 

Regards
