### ISSUE TITLE
Store Reports Last Used Checkboxes

### ISSUE THREAD

**Issue by sweitmann** [ledger123/runmyaccounts#170]
As discussed in Lahore.

**Comment by ledger123** [comment]
Hi Sebastian,

I have added the last used checkboxes functionaltiy in following reports:

1. ar transactions/outstanding
2. ap transactions/outstanding
3. balance sheet
4. income statement

A new table 'lastused' is needed in the database and for that I have also added upgrade script.

Final code is merged into develop for @phkroll review and merging to master.

Regards

**Comment by sweitmann** [comment]
Hi Armaghan, 

Thank you! Wonderful, closing this ticket now. 

Regards

**Comment by phkroll** [comment]
is merged to develop & integration
