### ISSUE TITLE
Add sales invoice variables to reminder module and allow sorting by column

### ISSUE THREAD

**Issue by sweitmann** [ledger123/runmyaccounts#172]
As discussed in Lahore.

**Comment by sweitmann** [comment]
Hi Armaghan, currently, when we print reminders to que the screen that appears thereafter is empty. It looks like this:
![Bildschirmfoto 2020-03-13 um 14 30 49](https://user-images.githubusercontent.com/100664/76625331-46950780-6537-11ea-836e-5a03be72f86d.png)

Instead it should look like this:
![Bildschirmfoto 2020-03-13 um 14 30 35](https://user-images.githubusercontent.com/100664/76625356-57457d80-6537-11ea-94ca-a89ee103ea50.png)

Regards

**Comment by ledger123** [comment]
Hi Sebastian,

This functionality has been implemented by allowing users to attach invoices in ticket #154. Any further changes we can discuss in that ticket.

So this ticket can be closed now.
