### ISSUE TITLE
Add release date as version indicator

### ISSUE THREAD

**Issue by sweitmann** [ledger123/runmyaccounts#173]
Hi Armaghan,

We need to add some kind of version info, which makes it possible to easily check the version that is running. As you suggested during our discussion about this in Lahore the date of release into the develop branch would probably be the best indicator.

Regards

**Comment by ledger123** [comment]
Hi Sebastian,

As we have decided in last few weeks, we are not merging into develop anymore and it will be done by Philipp by first testing in the respective branch. That means he will be updating release date whenever he will merge.

Regards
