### ISSUE TITLE
Rounding issue after posting payment

### ISSUE THREAD

**Issue by sweitmann** [ledger123/runmyaccounts#175]
As discussed in Lahore we need to increase rounding from 2 to 4 or 6 digits during calculation, in order to avoid rounding issues occurring when posting foreign currency payment.

**Comment by ledger123** [comment]
Hi Sebastian, this is fixed and also seems to be working in my testing.

Please test and confirm.

Regards

**Comment by sweitmann** [comment]
Hi Armaghan, 

Beautiful, you have done it again. Works like clockwork now, thanks! 

Please release to develop.

Regards

**Comment by ledger123** [comment]
Hi Sebastian,

Merged to developed and pushed to github.

Regards
