### ISSUE TITLE
Set reply to address and envelop address to customers email address from defaults

### ISSUE THREAD

**Issue by sweitmann** [ledger123/runmyaccounts#178]
As discussed with Thomas in Lahore.

**Comment by ledger123** [comment]
Hi Sebastian,

This was fixed and test by you as discussed on slack.

Also merged into develop. You can close this ticket now.

Regards

**Comment by sweitmann** [comment]
Wonderful, thanks Armaghan! 

Regards

**Comment by ledger123** [comment]
Hi Sebastian,

As discussed on slack, I have added a defaults setting which is disabled by default and this function can be enabled by checking that setting.

Code pushed to github and also munshi10 updated.

Regards

**Comment by sweitmann** [comment]
Hi Armaghan,

Opening this ticket again, because Thomas just reminded me that the envelope address part of this ticket has not yet been done. 

Regards

**Comment by sweitmann** [comment]
And today Philipp asked me to also add 'Validate email addresses before sending from SQL-Ledger'. Currently it's possible to send emails to addresses like 'sebastian@.com'.

**Comment by ledger123** [comment]
Hi Sebastian,

Email validation code is quite simple to add. We just need to add the two lines below to get email validated.

    use Email::Valid;
    $form->error("Invalid email address!") if !Email::Valid->address($form->{email}, -mxcheck => 1);

In my munshi10 code, I am doing validation when added a new customer/vendor/user. Should I do the same in rma code?

In my opinion, validating email address before sending invoices will not be particularly very helpful as that invoice will never go to anyone.

Kindly suggest.

**Comment by ledger123** [comment]
Hi Sebastian, 

I have added code in 178_validate_email to do the validation and and in my testing it is working perfectly.

Please test at your convince.

Regards

**Comment by sweitmann** [comment]
Hi Armaghan, 

Thank you! I have asked Philipp to release this one and will keep you updated. 

Regards

**Comment by phkroll** [comment]
I created a PR and added my testing comment there. Should be fixed before it's able to be merged to develop I'd say.

**Comment by ledger123** [comment]
Hi @phkroll , I have fixed the code as per your comment so that now multiple emails in the single field are validated correctly.

Please have a look and confirm your testing.

Regards

**Comment by phkroll** [comment]
Hey Armaghan, Tahnk you for the adjsutments, looks good to me and I , merged it :)
