### ISSUE TITLE
Convert LaTeX file in tmp folder to UTF-8

### ISSUE THREAD

**Issue by sweitmann** [ledger123/runmyaccounts#179]
Hi Armaghan,

As discussed over Slack we need to add a workaround for the Swiss QR-Code. 

Regards

**Comment by ledger123** [comment]
Hi Sebastian,

This is done and updated in 179_convert_latex_file_in_tmp_folder_to_utf8 branch.

Please test this with debuglatex variable enabled in sql-ledger.conf

Regards

**Comment by ledger123** [comment]
Hi Sebastian,

I have also added defaults setting and merged to develop.

Regards
