### ISSUE TITLE
Despatch method feature

### ISSUE THREAD

**Issue by sweitmann** [ledger123/runmyaccounts#18]
Some customers prefer to receive their invoices by email and others prefer to receive their invoices printed out on paper. 

A new "Dispatch method" customer master data setting would allow the user to individually set the preferred invoice dispatch method.

The optional dispatch methods could be set in a menu entry like 'System--Dispatch methods' and then individually set for each customer in 'AR--Customers--Add Customer'.

**Comment by ledger123** [comment]
Ok, as I get it this is just a setting for information only or do we need to use this setting on some screen?

Regards

**Comment by ledger123** [comment]
Hi Sebastian,

This feature has been added to customers and also there is a filter to select transactions based upon dispatch method in Batch printing /email.

Regards

**Comment by sweitmann** [comment]
Hi Armaghan,

Fantastic. Looks great. Thanks Armaghan. Closing this ticket now.

Regards

**Comment by ledger123** [comment]
Hi Sebastian,

As discussed on skype I have created new branch '018_despatch_method_feature'. This is also off master so that it can be quickly tested and merged.

Regards

**Comment by sweitmann** [comment]
Hi Armaghan,

When I run 'AR--Customers--Add Customer' I get the following error message:

![bildschirmfoto vom 2016-04-25 17 26 00](https://cloud.githubusercontent.com/assets/100664/14789021/e81121c4-0b0a-11e6-9ea8-7a2e047bb975.png)

Any ideas?

Regards

**Comment by sweitmann** [comment]
Hi Armaghan,

Tested and approved. Works beautifully, like all your work. Thanks! Can you deliver to develop, so that we can release this feature?

Regards
