### ISSUE TITLE
Adjustable user settings per database

### ISSUE THREAD

**Issue by sweitmann** [ledger123/runmyaccounts#19]
All user settings (including language, number format, access control etc.) should be individually adjustable for each database by a selected admin user.

Basic idea: Individual user management per database as in 3.0 instead of current overall user management for entire server.

**Comment by ledger123** [comment]
Hi Sebastian,

I have created new branch 'user-management' and pushed first commit which allows to add, modify users for the logged in database as well as change menu access settings.

Some variables still need to be worked out which will be done in second commit and then I shall ask you for the testing. (You can also test only but some settings like date style, language etc. are not editable yet)

Regards
