### ISSUE TITLE
Cosmetic rounding feature

### ISSUE THREAD

**Issue by sweitmann** [ledger123/runmyaccounts#191]
Hi Armaghan, 

As discussed on Slack please add the cosmetic rounding feature to ledgerdoctor. 

Regards

**Comment by ledger123** [comment]
Hi Sebastian,

Here are these queries for the record and further tuning. This set of queries was recommended by me on slack.

<code>
UPDATE ar SET amount=ROUND(amount::numeric,2), netamount = round(netamount::numeric,2), paid=ROUND(paid::numeric,2), fxamount = ROUND(fxamount::numeric,2), fxpaid = ROUND(fxpaid::numeric,2) WHERE amount - paid BETWEEN 0.0009 AND 0.009;
</code>

<code>
UPDATE ar SET amount=ROUND(amount::numeric,2), netamount = round(netamount::numeric,2), paid=ROUND(paid::numeric,2), fxamount = ROUND(fxamount::numeric,2), fxpaid = ROUND(fxpaid::numeric,2) WHERE paid - amount BETWEEN 0.0009 AND 0.009;
</code>

**Comment by ledger123** [comment]
Here are queries which were modified by Philpp and shared on channel.
```sql
-- get all posted ar's since xxx where books are not closed
select id from ar 
where id in (select distinct(trans_id) from audittrail where tablename = 'ar' and transdate >= '2020-03-24' and transdate < '2020-05-20' and action = 'posted')
and transdate > (select cast(fldvalue as date) from defaults where fldname = 'closedto');

-- round ar amounts to 2 digits where (insert upper query)
UPDATE ar 
SET amount=ROUND(amount::numeric,2), netamount = round(netamount::numeric,2), paid=ROUND(paid::numeric,2), fxamount = ROUND(fxamount::numeric,2), fxpaid = ROUND(fxpaid::numeric,2) 
WHERE id in (get all ar posted since and books not closed);
```
