### ISSUE TITLE
** DCN field data in 'Import--General Ledger' script

### ISSUE THREAD

**Issue by sweitmann** [ledger123/runmyaccounts#20]
Add possibility to import DCN field data in 'Import--General Ledger' script.

**Comment by ledger123** [comment]
There is no DCN column on GL screen. Do you want to put it in description or notes column?

**Comment by sweitmann** [comment]
You are right! Sorry, my mistake. It should be 'Import-Sales Invoices', not GL.

**Comment by ledger123** [comment]
I have added this column and dcn can be imported now from csv.

Please note that when an invoice is reposted, DCN is regenerated from all the variables. This should not be a problem if the imported DCN follows the variable pattern added for new invoices DCN.

Regards

**Comment by sweitmann** [comment]
Tested. Works perfect. Thanks, Armaghan! Closing this ticket now.
