### ISSUE TITLE
Number format - Amount changes

### ISSUE THREAD

**Issue by sweitmann** [ledger123/runmyaccounts#218]
Hi Armaghan,

When I have my number format preferences set to 1.000,00 and I search for example 29,50 in 'General Ledger--Search' this works fine:

![Bildschirmfoto 2020-09-30 um 11 02 35](https://user-images.githubusercontent.com/100664/94665472-7ad1e900-030c-11eb-8fc5-b44cec92cdcf.png)
 
If I edit one of the transactions and 'Post' or 'Post as new' the following page shows a different amount and thus the transactions corresponding to the first search no longer show up on screen:

<img width="935" alt="Bildschirmfoto 2020-09-30 um 11 06 56" src="https://user-images.githubusercontent.com/100664/94665952-15322c80-030d-11eb-9c9f-6f0d328fcf2f.png">

Regards

**Comment by ledger123** [comment]
Hi Sebastian, this is fixed in develop branch.

Kindly check at your convenience.

Regards

**Comment by sweitmann** [comment]
Hi Armaghan,

Fantastic, really appreciated. Thank you!

Regards
