### ISSUE TITLE
Company Name disappears in trial balance

### ISSUE THREAD

**Issue by sweitmann** [ledger123/runmyaccounts#219]
Hi Armaghan,

When I run a trial balance and drill down a certain account I can see the company name: 

![Bildschirmfoto 2020-09-30 um 11 13 22](https://user-images.githubusercontent.com/100664/94666614-f84a2900-030d-11eb-8973-b2d402d6170a.png)

If I open a booking and 'Post' or 'Post as new' the next screen doesn't show the company name any more:

![Bildschirmfoto 2020-09-30 um 11 14 51](https://user-images.githubusercontent.com/100664/94666761-2d567b80-030e-11eb-9b0e-2c8f7863ea69.png)

Regards
Sebastian

**Comment by ledger123** [comment]
Hi Sebastian, this is also fixed in develop branch.

Kindly check at your convenience.

Regards

**Comment by sweitmann** [comment]
Hi Armaghan, 

Wonderful, thank you!

Closing this ticket now.

Regards
