### ISSUE TITLE
Add email address to AR transactions report

### ISSUE THREAD

**Issue by sweitmann** [ledger123/runmyaccounts#229]
Hi Armaghan,

In order not to loose track of this issue (as posted on Slack on October 22nd) I'm also posting it here: 

b.) The user should be given an option to show the customer’s email address in the AR transactions / open reports in a separate row (not activated by default).

Regards

**Comment by ledger123** [comment]
Hi Sebastian,

This is done and here are screen shots showing this:

![Selection_010](https://user-images.githubusercontent.com/13597/116853220-2464ba00-ac0f-11eb-8f31-36e2181789ea.png)
![Selection_011](https://user-images.githubusercontent.com/13597/116853224-2595e700-ac0f-11eb-88aa-3d409acf81c8.png)

**Comment by ledger123** [comment]
Hi Sebastian,

Merged into develop and code pushed to github.

Regards
