### ISSUE TITLE
Check for closed books before import

### ISSUE THREAD

**Issue by sweitmann** [ledger123/runmyaccounts#230]
Hi Armaghan,

In order not to loose track of this issue (as posted on Slack on October 22nd) I'm also posting it here:

c.) If an imported Customer invoice (probably also other kinds of bookings) is imported via CSV, the import algorithm does not check if the accounts are closed or not. This results in a hastle if the import is booked into an already closed period. If a user wants to import something to a period which has been closed through the audit control, an error should be thrown telling the user, that the books are already closed for the date the booking is intended.

Regards

**Comment by sweitmann** [comment]
Hi Armaghan, 
Thanks! On a second thought I think we will also need to implement this feature for the other import modules that could effect the accounting, like Payments, AR/ AP Transactions and General Ledger. 
Would that be possible?
Regards

**Comment by sweitmann** [comment]
Hi Armaghan, 

Perfect, thanks. Please release to develop. 

Regards

**Comment by ledger123** [comment]
Hi Sebastian,

This code is merged and pushed.

Regards
