### ISSUE TITLE
Add 'Decimalplaces' to Trial Balance, Account Sheet and Journal

### ISSUE THREAD

**Issue by sweitmann** [ledger123/runmyaccounts#242]
Hi Armaghan, 

In some cases SQL-Ledger's float values result in totals with decimal places that don't correspond to the numbers shown on screen. In such cases it's helpful to be able to change the amount of decimal places in a report.

We already have this in Balance Sheet and Profit & Loss, but it would also be nice to have in Trial Balance, Account Sheet and Journal. 

Would that be possible? 

Regards

**Comment by ledger123** [comment]
Hi Sebastian,

This is added. Now will wait for your advice for moving forward.

Regards
