### ISSUE TITLE
Remove AP invoices check from Ledger Doctor

### ISSUE THREAD

**Issue by sweitmann** [ledger123/runmyaccounts#243]
Hi Armaghan, 

In 'System-Ledger Doctor' we have the "AP invoices with rounding difference" check that doesn't make sense. I can't remember what the issue was and why we added this check in the first place. Can you?

![Bildschirmfoto vom 2021-04-15 08-35-05](https://user-images.githubusercontent.com/100664/114825236-3e586d00-9dc6-11eb-833a-3fe36c56bda3.png)

If not, perhaps we could simply remove it to clear screen a bit? 

Regards

**Comment by sweitmann** [comment]
Hi Armaghan, 

Wonderful, thanks! Please release to develop.

Regards
Sebastian

**Comment by ledger123** [comment]
Hi Sebastian,

Merged into developed and pushed.

Regards
