### ISSUE TITLE
<%bankname%> not in CAPITAL LETTERS 

### ISSUE THREAD

**Issue by sweitmann** [ledger123/runmyaccounts#244]
Hi Armaghan,

As for now the <%bankname%> variable which is entered in 'System--Bank Accounts' is always shown and printed in CAPITAL LETTERS. 

This should no longer be the case. Instead it should be written as saved. 

Regards

**Comment by sweitmann** [comment]
Hi Armaghan, 

Beautiful, thanks! Please release to develop. 

Regards

**Comment by ledger123** [comment]
Hi Sebastian,

This is merged in developed and pushed to github.

Regards

**Comment by ledger123** [comment]
Hi Sebastian,

This is done. I have also removed upper case from BIC and IBAN.

Regards

**Comment by sweitmann** [comment]
Wonderful, thank you Armaghan! 

Regards

**Comment by sweitmann** [comment]
And please release to develop.
