### ISSUE TITLE
New variable <%discountrate_percent%>

### ISSUE THREAD

**Issue by sweitmann** [ledger123/runmyaccounts#245]
Hi Armaghan,

Today we have the variable <%discountrate%> which, if you have deducted 25% discount for a certain article, would show as 25 in templates. 

We need a new variable <%discountrate_percent%> which should show 25% instead of just 25 in templates when giving 25% discount on certain article. 

Regards

**Comment by ledger123** [comment]
Added and here is screen shot using $form->dumper to displace variable values.

![Selection_NNN(001)](https://user-images.githubusercontent.com/13597/116063054-f24ad980-a69d-11eb-8c6a-c106e21d4ec7.png)

**Comment by sweitmann** [comment]
Hi Armaghan,

Perfect, thanks. Please release to develop. 

Regards

**Comment by ledger123** [comment]
Hi Sebastian,

Merged and pushed to github.

Regards

**Comment by sweitmann** [comment]
Hi Armaghan, 

I am opening this ticket again, because Thomas is having problems with this variable in Sales Orders and Quotations. 

I have done some testing and found that when I use html template and print <%discountrate_percent%> in Sales Invoice it shows 10\% on screen, whereas in Sales Order it simply shows 10% on screen. 

Do you think this could be what's causing the problem? Is there a difference between how this variable is created in Sales Invoice vs. Sales Order and Quotation?

Regards

**Comment by ledger123** [comment]
Hi Sebastian,

I have fixed this issue. This was taken care of in sales invoice but not in sales orders and quotations. Now sales orders are ok too.

Added and committed in develop branch.

Regards

**Comment by sweitmann** [comment]
Hi Armaghan, 

Wonderful, thank you! 

Closing this ticket again. 

Regards
