### ISSUE TITLE
Float Values - Fractional total of zero accounts 

### ISSUE THREAD

**Issue by sweitmann** [ledger123/runmyaccounts#247]
Hi Armaghan, 

As discussed, in our current fractional total of zero accounts branch, next we shall remove 8 digit rounding from balance sheet, profit & loss and trial balance. Please also add the possibility to increase "Decimalplaces" in trial balance. 

This will allow us to prove that float values are causing the small differences between profit & loss and balance sheet that might exist in some databases. 

Regards

**Comment by sweitmann** [comment]
Hi Armaghan, 

Thanks for reverting the commit. 

We need to look into this one a little further, so I'm opening this ticket again. 

Regards

**Comment by sweitmann** [comment]
Hi Armaghan, 

I have restored a database as "backup" on our common server and when I run a trial balance for 2020 with branch #247 I get a total of 11.762.238,10 in both debit and credit.

If I run the same report in master branch I get 11.762.238,09. 

As I understood our work on 247 we simply made it possible to show the accounts with fractional difference in profit and loss and balance sheet. 

How come it also influences the totals of trial balance?

Regards

**Comment by sweitmann** [comment]
![Bildschirmfoto 2021-11-05 um 10 27 46](https://user-images.githubusercontent.com/100664/140488746-94054f71-6632-4e0c-bca7-d70c8cc6fd93.png)
![Bildschirmfoto 2021-11-05 um 10 28 02](https://user-images.githubusercontent.com/100664/140488753-03a7f16d-f9d0-4c37-bd79-2c2a13a23914.png)

**Comment by ledger123** [comment]
Hi Sebastian,

I have added trial 3 in the test code after two decimals rounding. Please have a look and confirm if these are the correct fractional figures we are going to post as adjustment transaction.

Code pushed to github in this branch but you can also test by switching to the branch on our common server.

Regards

**Comment by sweitmann** [comment]
Hi Armaghan, 

In order to understand trial 3 I started by looking at trial 1 and got confused. In the backup database on our common server I get the following on accounts 3200 and 3210 when I run a trial balance with 8 digit precision:

<img width="1116" alt="Bildschirmfoto 2021-11-25 um 11 57 34" src="https://user-images.githubusercontent.com/100664/143603583-20ac3ce7-14a8-4cd3-83d2-24773a545d01.png">

Instead in 'System--Fractional Correction Transaction' trial 1 I get this:

<img width="1000" alt="Bildschirmfoto 2021-11-25 um 11 58 09" src="https://user-images.githubusercontent.com/100664/143603607-26bc519f-b906-48e0-8f89-8df7fcb8f591.png">

Why are all the digits missing in trial 1? Shouldn't the numbers be the same in trial balance and trial 1?

Regards

**Comment by sweitmann** [comment]
Hi Armaghan, 

Thanks for adjusting the code! I just ran Fractional Correction Transaction feature and now you have got it all right. At this point we now have the correct adjustment amount in step 3.

I think the next step could be to take the correct amount in step 3 and book it in the automatically produced FRACTIONAL CORRECTION transaction.

What do you think?

Regards
