### ISSUE TITLE
Adjustments to 'AR--Customers--Customers Search' report

### ISSUE THREAD

**Issue by sweitmann** [ledger123/runmyaccounts#249]
Hi Armaghan,

The report mentioned above would need two small adjustments:

a.) Possibility to sort by 'Type' column
b.) If you marked the 'Address' checkbox, the report will show empty 'Address' columns, although the customers listed actually have an address saved. 

Regards

**Comment by ledger123** [comment]
Hi Sebastian,

I have added sorting by contact type.

I can already see address in the report so this does not seem to be the problem. Please have a look at the screen shot and 
 reconfirm.

Regards

![Selection_044](https://user-images.githubusercontent.com/13597/142981705-9bf67e3f-1b8b-41a1-93fd-cc85c089c121.png)

**Comment by sweitmann** [comment]
Hi Armaghan, 

Thank you for adding contact type sorting. 

You are right that address is already shown in the report, so this does not seem to have be the second problem. Have tried to go back and see what else it could have been and also discussed it with Thomas, unfortunately without success. 

So, please release to develop and then we will close this ticket. 

Regards

**Comment by ledger123** [comment]
Hi Sebastian,

Good morning.

Branch 249_customer_search_improvement is merged and pushed to github.

Regards

**Comment by sweitmann** [comment]
Hi Armaghan, 

Thank you! I will close this ticket now. 

Regards
