### ISSUE TITLE
** Add AR/AP transactions and "Total" to Customer/Vendor History reports

### ISSUE THREAD

**Issue by sweitmann** [ledger123/runmyaccounts#25]
Add the total amount for each customer/vendor to 'AR--Customers--Customer History' and 'AP--Vendors--Vendor History' reports.

And add the possibility to select report for AR/AP transactions for 'AR--Customers--Customer History' and 'AP--Vendors--Vendor History' reports.

**Comment by ledger123** [comment]
Hi Sebastian,

This has been added.

I could not understand the second part which I shall discuss on skype today.

Regards

**Comment by sweitmann** [comment]
Hi Armaghan,

Tested. You have solved the first part and it looks great. I will try to explain the second part better by adding pictures. 

a.) There are two reports under 'AR--Vendors': 'AR--Vendors--Vendors Search' and 'AR-Vendors--Vendors History':

![bildschirmfoto vom 2016-02-12 11 36 54](https://cloud.githubusercontent.com/assets/100664/13004836/1b516ba0-d17e-11e5-8fcc-c8f1b0e1f672.png)

b.) In the 'AR--Vendors--Vendors Search' report it's possible to select "AP Transactions":

![bildschirmfoto vom 2016-02-12 11 37 24](https://cloud.githubusercontent.com/assets/100664/13004875/532c3078-d17e-11e5-86f4-8c84b1580331.png)

c.) Whereas in the 'AR--Vendors--Vendors History' it's only possible to see the history for "Vendor Invoices", but not for "AP Transactions":

![bildschirmfoto vom 2016-02-12 11 37 50](https://cloud.githubusercontent.com/assets/100664/13004906/7feff536-d17e-11e5-91d7-ccb0ffaaae61.png)

It would be great if you could add the possibility to also see the history for "AP Transactions" under 'AR--Vendors--Vendors History'. And the same applies to 'AR--Customers--Customers History' and 'AR Transactions'.

Regards

**Comment by ledger123** [comment]
AR/AP Transactions have been added to the history reports and pushed to develop2 branch.

Regards

**Comment by sweitmann** [comment]
Hi Armaghan, 

Tested and very nice! This is a great feature for RMA customers. Thanks for all your fantastic support and for solving this one too. It's both an honor and a pleasure to work with you.

Regards
