### ISSUE TITLE
'Invoice Date' and 'Due Date' instead of 'Aged' and 'Overdue'

### ISSUE THREAD

**Issue by sweitmann** [ledger123/runmyaccounts#250]
Hi Armaghan, 

Our support has informed us that there is a lot of confusion regarding the terms 'Aged' and 'Overdue' in the 'AR--Reports--AR Aging' module. They have suggested that we rename the two as follows:

'Aged' -> 'Invoice Date'
'Overdue' -> 'Due Date'

Please adjust at your convenience and feel free to do this directly in develop branch. 

Regards

**Comment by ledger123** [comment]
Hi Sebastian,

This can be done in the translation. Do you still need to be done in the code?

Regards

**Comment by sweitmann** [comment]
Hi Armaghan, 

Thank you for your valid question. 

Only changing it in the translation files would not solve this problem in the English version right? Because Run my Accounts also use the English version for foreign customers. 

And then it would also change the word 'Overdue' into 'Due Date' in the am.pl module right?
![Bildschirmfoto 2021-08-30 um 17 51 38](https://user-images.githubusercontent.com/100664/131367934-f9fb2964-4d67-402e-bc67-c20cff6d53f3.png)

Not sure if it also makes sense change it there. 

So, if it's not too much hassle, perhaps changing it in the code will keep things more consistent?

Regards

**Comment by ledger123** [comment]
Hi Sebastian,
It is a quick change actually but just thought of that option.

It is done and pushed in the linked branch.

Regards

**Comment by sweitmann** [comment]
Hi Armaghan, 

Perfect, thanks! Looks beautiful now. Please release to develop.

Regards
