### ISSUE TITLE
Disallow unbalanced bookings and make ledgerdoctor trace them if any

### ISSUE THREAD

**Issue by sweitmann** [ledger123/runmyaccounts#255]
Hi Armaghan, 

As discussed today we need to disallow unbalanced bookings like this one:

![Bildschirmfoto 2021-08-11 um 13 43 58](https://user-images.githubusercontent.com/100664/129023137-829d16a1-c352-4809-a0d1-507a20754eed.png)

And it would be great if we could add a query to ledgerdoctor to find such bookings if any. 

Regards

**Comment by ledger123** [comment]
Hi Sebastian,

This is done and pushed to github in the branched linked to this ticket. I have increased precision to 8 if it is less to check for the unbalanced journal.

Regards

**Comment by ledger123** [comment]
Hi Sebastian,

I have modified ledgerdoctor as required. I have done this change in develop branch directly since it was a very minor thing and will get merged quickly whenever develop is merged into master.

Regards

**Comment by sweitmann** [comment]
Hi Armaghan, 

Perfect, thank you! Please feel free to release #255 to develop. 

Regards

**Comment by ledger123** [comment]
Merged to develop. I am closing this ticket now.
