### ISSUE TITLE
Add projects to 'Import--General Ledger'

### ISSUE THREAD

**Issue by sweitmann** [ledger123/runmyaccounts#257]
Hi Armghan, 

Please add projects to 'Import--General Ledger'. Thank you!

![Bildschirmfoto 2021-08-12 um 10 49 58](https://user-images.githubusercontent.com/100664/129168249-e34e859c-5e5a-48ca-983f-23855f0f612f.png)

Regards

**Comment by sweitmann** [comment]
Hi Armaghan, 

Thank you! Tested, but for some reason I can't get it to work. 

a.) When I read the file the projectnumber is shown in the last column:
![Bildschirmfoto 2021-08-19 um 16 03 49](https://user-images.githubusercontent.com/100664/130082848-bfd2ddd4-a8fd-45e3-920f-fb36264c8d75.png)

b.) But when I open the booking after import the projectnumber is not booked:
![Bildschirmfoto 2021-08-19 um 16 04 21](https://user-images.githubusercontent.com/100664/130082949-274f752a-1f5b-4ff8-a162-b0ca77b5f456.png)

Any ideas?

Regards

**Comment by ledger123** [comment]
Hi Sebastian,

You were right. There was an issue but not sure how I thought it was done.

It is corrected now. Here is screen shot and CSV file I used for testing.
![Screenshot from 2021-08-29 17-35-11](https://user-images.githubusercontent.com/13597/131250565-f84e5b26-5d75-48d9-885a-9f67ecae374c.png)
[gl.csv](https://github.com/ledger123/runmyaccounts/files/7072489/gl.csv)

Regards

**Comment by sweitmann** [comment]
Hi Armaghan,

Wonderful, thanks! Works beautifully now. 

Please release to develop. Thank you!

Regards
