### ISSUE TITLE
Sales Invoices without tax don't show up in Line Tax Report

### ISSUE THREAD

**Issue by sweitmann** [ledger123/runmyaccounts#261]
Hi Armaghan, 

When we book 'AR--**AR Transactions**' without tax they **are listed** as "Non-taxable" transactions in the 'System--Line Tax Report'. 

But when we book 'AR--**Sales Invoices**' without tax they **are not listed** at all in the 'System--Line Tax Report'. 

Could you please confirm and correct at your next convenience? Thank you!

Regards

**Comment by sweitmann** [comment]
Hi Armaghan, 

When we start working on this ticket it would be great if we could also add currency and 'Include Exchange Rate Difference' checkbox to 'System--Line Tax Report'. 

Sometimes we have Swiss CHF accountings that have bookings in EUR (foreign currency) and that need to file VAT returns in EUR. In such cases these two new features would be of enormous help. 

Regards

**Comment by ledger123** [comment]
Hi Sebastian,

I have corrected this report and now I can see non-taxable invoices in the report. Kindly confirm this and then I shall add the exchange rate difference too.

Regards

**Comment by sweitmann** [comment]
Hi Armaghan, 

Thank you! Whilst testing I noticed another issue in the 'System--Line Tax Report': It shows non-taxable AP Transactions twice. You see this as below if you checkout test4 booking in Line Tax Report for November in backup2 database on https://ledger123 server:
<img width="1082" alt="Bildschirmfoto 2021-11-24 um 17 34 14" src="https://user-images.githubusercontent.com/100664/143278847-924f00b6-1614-4875-8042-3e931012297a.png">

Would be great if you could fix that too now that you are at it. Thanks a million.

Regards

**Comment by sweitmann** [comment]
Hi Armaghan, 

One more thing: We don't need to add the 'Include exchange rate difference' feature. I have given it some more thought and don't think it will work, since only payment accounts include exchange rate difference. Values booked on articles and I guess also tax accounts are simply calculated with exchange rate. 

We can discuss this in depth over Nextcloud if you like or if I have misunderstood something. 

Regards

**Comment by ledger123** [comment]
Hi Sebastian,

I have corrected the duplicate ap invoice issue and and tested on the backup2 db. Please have a look and confirm.

Yes, you are right. I got it regarding the exchange rate.

Regards

**Comment by IbrahimSaqib24** [comment]
Hi Armaghan,

Tested. Please release to develop.

Regards.

**Comment by ledger123** [comment]
Hi @phkroll ,

I have updated this branch with all latest develop changes but as discussed last time on slack, I am not merging it on develop so that you can test this in this branch and merge it yourself.

Regards

**Comment by phkroll** [comment]
Hey @ledger123 

I have some error in the new report:
![Bildschirmfoto 2022-05-02 um 15 47 07](https://user-images.githubusercontent.com/5967878/166244622-f9f3fa94-5791-45a2-983e-f8cb49532484.png)

**Comment by sweitmann** [comment]
Hi Armaghan, 

I don't understand why the fractional difference ticket is being handled here, because I think this ticket is only about this fix:
https://github.com/ledger123/runmyaccounts/commit/41482f2a41c8fb42b2882c367d9bbe1545696e3c which is related to non-taxable invoices not showing up in line tax report. 
And now I would need your help to continue working on the non-taxable invoices that don't show up in the line tax report. 
I have just noticed that when a sales invoice contains both taxable and non-taxable articles it only show one of the two in the line tax report. 

Regards

**Comment by sweitmann** [comment]
Thank you, Armaghan! Closing this ticket now.
