### ISSUE TITLE
Incorrect dates in projects summary drilldown

### ISSUE THREAD

**Issue by ledger123** [ledger123/runmyaccounts#267]
Hi Sebastian, 

As discussed with you on nextcloud.

Regards

**Comment by sweitmann** [comment]
Hi Armaghan, 

Perfect, thanks. Here is the link to the RMA ticket for future reference:
https://projects.runmyaccounts.com/redmine/issues/103891

Regards

**Comment by sweitmann** [comment]
Hi Armaghan, 

Philipp has approved. Please release to develop and feel free to close this ticket. 

Regards

**Comment by ledger123** [comment]
Hi Sebastian,

Merged to develop and pushed to github.

Regards
