### ISSUE TITLE
HTML_MIME_NO_HTML_TAG

### ISSUE THREAD

**Issue by sweitmann** [ledger123/runmyaccounts#268]
Hi Armaghan, 

We still have some spam problems with documents sent by mail from SQL-Ledger, even when using Sendinblue. Some of the problems are related to the DNS settings and these will be resolved by Philipp. Other problems are related to HTML and these will be resolved by Thomas. 

The thing we need to solve in SQL-Ledger is related to the reference HTML_MIME_NO_HTML_TAG. This message seems to point out that we don't have a HTML Tag in the mailer. Would you agree? And is this something you could add?

Thomas gave me a hint that he had found more information about this issue here:
https://stackoverflow.com/questions/1860937/how-can-i-lower-the-spam-score-of-my-email-message

And he also sent me this picture:
![Bildschirmfoto 2021-10-20 um 15 16 45](https://user-images.githubusercontent.com/100664/138100294-e84707b0-d53a-4c69-ae55-07b63692c0e4.png)

Let me know if you need any further information. 

Regards

**Comment by sweitmann** [comment]
Hi Armaghan, 

Thank you for your swift and excellent support! Philipp has merged this code, so I'm closing this ticket now.  

Regards

**Comment by sweitmann** [comment]
Hi Armaghan, 

I am reopening this ticket, because Philipp asked me to make sure we don't forget the following:

![Bildschirmfoto 2021-12-01 um 13 36 24](https://user-images.githubusercontent.com/100664/144235594-cc45acda-b44a-4bf5-a2b9-7f88e72f3050.png)

Please give me a sign when this has been done and I will then close this ticket again. Thank you!

Regards

**Comment by phkroll** [comment]
Hey Together,

We recently had to fix an issue with linebreaks.
When investigating the issue, we figured out that it is because of some stuff we send wrongly to sendinblue, by that we also saw how to provide the textversion to sendinblue and did it in the same turn.
So this can be closed.

https://github.com/ledger123/runmyaccounts/commit/c09b730368f41176f5a9031bb7574dbe16c4fd2b

Regards,
Philipp
