### ISSUE TITLE
** First customer/ vendor without tax accounts

### ISSUE THREAD

**Issue by sweitmann** [ledger123/runmyaccounts#27]
After having setup a new database and entered the first customer or vendor, it is not possible to select a tax account (Line Tax) in the very first transaction.

Allthough the customer has been setup with tax, the tax accounts don't show up in the first transaction, neither in the Line Tax drop-down menu, nor with the tax totals below.

![bildschirmfoto 2015-11-20 um 15 35 53](https://cloud.githubusercontent.com/assets/100664/11302230/6d4af49a-8f9c-11e5-8342-72a7a37b8efd.png)

The tax accounts only appear once you have entered the first amount and updated the screen. And then they only appear as totals below, not in the Line Tax drop-down menus.

![bildschirmfoto 2015-11-20 um 15 46 14](https://cloud.githubusercontent.com/assets/100664/11302463/e2c94e50-8f9d-11e5-838b-de72592971b5.png)

Is there any way to display and enable the selection of tax accounts also in the very first transaction?

Regards

**Comment by ledger123** [comment]
I have fixed it.

But the user will still need to select a customer and press Update for taxes to appear as when the screen opens, we don't know any customer.

Is that ok or we need to do something about it?

**Comment by sweitmann** [comment]
Perfect. Looks great. Thanks, Armaghan! I'm closing this ticket now.
