### ISSUE TITLE
** Include Exchage Rate Difference "drops out" after re-posting listed transaction

### ISSUE THREAD

**Issue by sweitmann** [ledger123/runmyaccounts#28]
If you run the 'General Ledger--Reports--Kontenblatt' report without un-checking the "Include Exchange Rate Difference" box and then open one of the listed foreign value transactions and re-post it, the report will subsequently list the transactions without "Exchange Rate Difference".

1.) 
![bildschirmfoto 2015-11-20 um 15 59 46](https://cloud.githubusercontent.com/assets/100664/11302836/db844efe-8f9f-11e5-9850-077bb395cc94.png)

2.)
![bildschirmfoto 2015-11-20 um 16 00 02](https://cloud.githubusercontent.com/assets/100664/11302842/e233240a-8f9f-11e5-89d3-ecc4461089b9.png)

3.) 
![bildschirmfoto 2015-11-20 um 16 00 13](https://cloud.githubusercontent.com/assets/100664/11302852/ec42403e-8f9f-11e5-8a61-897f8007f79a.png)

4.)
![bildschirmfoto 2015-11-20 um 16 00 24](https://cloud.githubusercontent.com/assets/100664/11302859/f55d5212-8f9f-11e5-8b78-27e6c26594b3.png)

Regards
Sebastian

**Comment by ledger123** [comment]
This has been fixed and pushed to github.

**Comment by sweitmann** [comment]
Tested. Works beautifully. Thanks, Armaghan. Closing this ticket now.
