### ISSUE TITLE
Add Latex variables to sales quotations sales order modules

### ISSUE THREAD

**Issue by tbraendle** [ledger123/runmyaccounts#280]
The following latex variables are not available in sales quotations sales order modules. It would be great, if these were added: 

- <%company%>
- <%companyaddress1%>
- <%companyaddress2%>
- <%companyzip%>
- <%companycity%>
-

**Comment by sweitmann** [comment]
And also <%companycountry%>. Thank you!

Regards

**Comment by ledger123** [comment]
Hi Thomas,

All these variables added and tested with debug command as shown in screenshot. Kindly check and confirm in 280_new_latex_varialbles_in_orders_quotes branch.

Regards

![Selection_059](https://user-images.githubusercontent.com/13597/143993033-013208df-6d71-456b-8e5e-58bba861976b.png)

**Comment by phkroll** [comment]
Merged.
