### ISSUE TITLE
*** New variables in Reminder template

### ISSUE THREAD

**Issue by sweitmann** [ledger123/runmyaccounts#29]
Everything works fine, but to be consistent with the naming of these variables in other templates, could you please adjust the names:

From <%bankrvc%>  to <%rvc%>
from <%bankdcn%> to <%dcn%> and
from <%bankdcn group=5right%> to <%dcn group=5right%>

Regards

**Comment by ledger123** [comment]
Hi Sebastian,

Fixed and basic testing done using app.myledger.net/ledger123/rma installation.

Regards

**Comment by sweitmann** [comment]
Tested and approved. Works perfect now. Thanks Armaghan. Closing this ticket now.

**Comment by sweitmann** [comment]
I'm opening this ticket again, since I remember that we had an issue with these variables ending up on the wrong reminder, if one of them did not contain any <%rvc%> and <%dcn%> information.

**Comment by ledger123** [comment]
Hi Sebastian,

I have fixed that reminders not showing up issue in the 029_new_vars_in... branch so that you can now continue the testing.

Regards

**Comment by sweitmann** [comment]
Hi Armaghan, 

When I print the invoice over 'AR--Reports--Transaction' I get the correct <%rvc%> and <%dcn%> printed on the PDF:

<%name%>\\
<%invnumber%>\\
<%rvc%>\\
<%dcn%>\\
<%dcn group=5right%>\\

![bildschirmfoto 2016-06-22 um 15 30 26](https://cloud.githubusercontent.com/assets/100664/16268416/a6abee56-388e-11e6-9ae0-dc097a04698d.png)
 But when I print a reminder over 'AR--Reports--Reminders' I get the wrong <%rvc%> and <%dcn%> printed on the PDF:

<img width="751" alt="bildschirmfoto 2016-06-22 um 15 24 52" src="https://cloud.githubusercontent.com/assets/100664/16269099/3eaa6e24-3891-11e6-9de2-f200654d88e7.png">
The correct variable content can be found in the Sales Invoice:
![bildschirmfoto 2016-06-22 um 15 54 03](https://cloud.githubusercontent.com/assets/100664/16269188/941dbaf0-3891-11e6-9ab3-c915a3361560.png)

Regards

**Comment by ledger123** [comment]
Hi Sebastian,

This seems to be fixed in my testing and code is pushed to github.

Regards

**Comment by sweitmann** [comment]
Tested and confirmed. Thanks, Armaghan. Closing this ticket now.
