### ISSUE TITLE
Language is not saved

### ISSUE THREAD

**Issue by sweitmann** [ledger123/runmyaccounts#290]
Hi Armaghan, 

When you select a language in the appropriate dropdown in a sales or vendor invoice and then post it, the selected language will be saved and displayed again next time you open that invoice again:

<img width="830" alt="Bildschirmfoto 2022-01-23 um 09 25 43" src="https://user-images.githubusercontent.com/100664/150670591-9be9724b-a71a-4911-8143-6dd8584e9b35.png">

This only works in sales and vendor invoices. Not in quotations, orders and AR/AP-transactions. 

Would it be possible to add this feature to those as well?

Regards

**Comment by ledger123** [comment]
Hi Sebastian,

This has been fixed and pushed to the github in the attached commit.

Regards

**Comment by sweitmann** [comment]
Hi Armaghan,

Thanks for fixing this. Unfortunately we now have another small issue. 

In the master version when I change the customer the language version is updated according to the settings in the customer master data. 

After your fix this feature seems to be broken, because now it does not change the language even when I switch the customer and the new customer has other language setting in his master data. 

It would be great if we could have both. That is:

a.) Language is set according to master data and

b.) if the language is changed it will be remember accordingly for that invoice or transaction. 

Would this be possible?

Regards

**Comment by ledger123** [comment]
Hi Sebastian,

It is fixed as needed and I have tested it in both invoices and transactions.

Kindly test at your convenience.

Regards

**Comment by phkroll** [comment]
merged to dev.
