### ISSUE TITLE
Line Tax Version: When Tax is changed followed by "Update", Tax Amount remains the same

### ISSUE THREAD

**Issue by sweitmann** [ledger123/runmyaccounts#3]
When Tax is changed followed by "Update" the Tax Amount remains the same and does not re-calculate accordingly. The calculated Tax Total actually switches to the correct tax account box, but the calculated tax remains the same:

![bildschirmfoto 2015-08-27 um 17 25 06](https://cloud.githubusercontent.com/assets/100664/9524700/a0b23a68-4ce0-11e5-9d49-2db378e50026.png)

**Comment by ledger123** [comment]
This is fixed and pushed to github.

**Comment by sweitmann** [comment]
Thanks, Armaghan. As discussed on the phone, could you please also adjust so that "Tax Amount" is recalculated if the base "Amount" is changed followed by a click on "Update". And the same thing should apply if "Tax Included" is marked followed by a click on "Update". In other words a click on "Update" should re-calculate all "Tax Amounts" according to any data changed.

**Comment by ledger123** [comment]
Hi Sebastian,

Now tax recalculation is done when we change tax included, amount and tax account. Kindly test and confirm.

Regards

**Comment by sweitmann** [comment]
Hi Armaghan,

Fantastic! Works perfect now. Thanks. Closing this ticket now. 

Regards
Sebastian
