### ISSUE TITLE
**** Deeplinking feature

### ISSUE THREAD

**Issue by sweitmann** [ledger123/runmyaccounts#30]
There is an urgent need for the possibility to deep link into SQL-Ledger. This includes the need to be able to open the SQL-Ledger menu in the deep linked position. 

Actually, we already have the possibility use hyperlinks to deep link into SQL-Ledger, but as this feature works today the menu doesn't open in the deep linked position.

With this new feature, it should for example be possible to deep link into the 'AR--Reports--Outstanding' report and at the same time have the menu open in this position:

![bildschirmfoto 2015-11-27 um 11 34 50](https://cloud.githubusercontent.com/assets/100664/11439326/ea93061e-94fa-11e5-93ba-474e8c711bbd.png)

**Comment by ledger123** [comment]
Hi Sebastian,

I finally figured out it is quite easy to simulate these clicks with jquery and successfully implented a test in my customized sql-ledger. I simulate two clicks on opening sql-ledger and a menu (HMS) and a submenu 'Video Tutorials' are opened right after login.

    $( "#menu1" ).trigger( "click" );
    $( "#menu8" ).trigger( "click" );

Right now the issue is to open the indiviual form and screen and for that we need to make some changes to the code to assign css ids to invidiual menu items. Nothing technical so hopefully I shall be able to do it next week.

Regards
![click](https://cloud.githubusercontent.com/assets/13597/11581206/431a0cb8-9a61-11e5-873c-bde3b6fe7e16.png)
![open](https://cloud.githubusercontent.com/assets/13597/11581207/431d8bfe-9a61-11e5-9e0b-4da2750a87a3.png)

**Comment by sweitmann** [comment]
Thanks, Armaghan. I discussed this with Nils today and he thinks we are on the right track. Let's talk about the next steps in our call on Tuesday.

Regards

**Comment by ledger123** [comment]
Hi Sebastian,

I have modified code to assign css ids to menu items and code pushed. Right now this code is not much useful except for demo like we can go to the desired menu with following code:

   $( "#menu1" ).trigger( "click" );
   $( "#menu6" ).trigger( "click" );
   $( "#menu8" ).trigger( "click" );

The number after 'menu' is serial number of the menu within the whole menu and can be viewed in browser with inspect element feature of the browser or viewing source.

The next thing is to actually pass this menu information to SL and generate the above code based upon the passed parameters. I am hoping to get it done by tomorrow.

Regards

**Comment by ledger123** [comment]
Hi Sebastian,

First implementation seems to work. You can  see demo by clicking on the following links:

1. This will highlight and open AR--Transactions report
http://app.myledger.net/ledger123/rma/login.pl?login=demo2@ledger28&password=demo2&action=login&js=1&menuids=1:6:7

2. This will highlight and open AR--Outstanding report
http://app.myledger.net/ledger123/rma/login.pl?login=demo2@ledger28&password=demo2&action=login&js=1&menuids=1:6:8

For any menu item we want to access this way, we will need to add its call back to to the $callback hash reference in menu.pl 'sub display' as shown in the attached image. And that is it.

Regards
![callbacks](https://cloud.githubusercontent.com/assets/13597/11862977/ea67f8f4-a4b1-11e5-9207-68a977f67d1f.png)

**Comment by sweitmann** [comment]
Wonderful solution. Thanks Armaghan! Nils will take it from here and I'm closing this ticket now.

**Comment by sweitmann** [comment]
Hi Armaghan,

as discussed today, we have two issues that need attending to:

1.) Instead of having a number after 'menu' as serial number of the menu within the whole menu, it would be great if we could use text according to the logic of menu.ini instead. For example "AR--Customers--Add_Customer";

2.) If a user doesn't have user rights for a certain menu item being accessed with the deep linking feature, the user should receive a "Access denied" message on the screen.

Regards

**Comment by ledger123** [comment]
Hi Sebastian,

1. First issue has been resolved. Now you can access the menu with a url like:

http://app.myledger.net/ledger123/rma/login.pl?login=demo2@ledger28&password=demo2&action=login&js=1&menuids=ar:ar_reports:ar_reports_outstanding

2. I am still figuring out the code for second point and let you know as soon as it is done; hopefully today or tomorrow.

Regards

**Comment by ledger123** [comment]
I have modified a code in the following way to display the access denied message.

1. Added a level variable to the callbacks in menu.pl.
2. Checking the access level in the module with a single line of code like I have done in bin/mozilla/aa.pl 'sub search'

Regards

**Comment by nsamuelsson** [comment]
Hi

A simple question: What would be the menu.pl entry for the income statement?

regards
Nils

**Comment by ledger123** [comment]
Hi Nils,

If I understand correctly, are you asking for the callbacks value? If so then it would be:

    rp.pl?action=report&level=General Ledger--Reports--Income Statement&js=1&report=income_statement

Basically you take whatever is shown in the status bar for any link and then remove the server/folder as well as path and login user name variables. I 'created' above line by modifying following which I copied from Right-click-Copy URL in browser.

     http://localhost/runmyaccounts/rp.pl?path=bin/mozilla&action=report&level=General%20Ledger--Reports--Income%20Statement&login=rma&js=1&report=income_statement

And if you are asking for something else, then please let me know.

Regards

**Comment by sweitmann** [comment]
Hi Armghan,

This one is up and running now. Great work, thanks a million. 

Closing this ticket.

Regards
