### ISSUE TITLE
Add department to 'Export--Export DATEV File' feature

### ISSUE THREAD

**Issue by ledger123** [ledger123/runmyaccounts#307]
As discussed on nextcloud.

**Comment by ledger123** [comment]
Hi Sebastian,

I have added department in the respective branch and pushed the code to github. This commit is attached to this ticket above.

Please have a look at your convenience.

Regards

![Selection_004](https://user-images.githubusercontent.com/13597/162117374-311ecd2f-d2ea-4f9c-ae5f-80d6d83e4dca.png)

**Comment by sweitmann** [comment]
Hi Armaghan, 

Please add optional "remove error line" feature. 

Regards

**Comment by ledger123** [comment]
Hi Sebastian,

This has been done and you can test in your convenience.

Regards

**Comment by sweitmann** [comment]
Hi Armaghan, 

Thank you! Checked and it works perfectly. 

Regards

**Comment by phkroll** [comment]
merged
