### ISSUE TITLE
*** Rounding difference booked on wrong account

### ISSUE THREAD

**Issue by sweitmann** [ledger123/runmyaccounts#31]
In an earlier fix from approx. 1,5 years ago, it was decided that certain rounding differences in AR and AP transactions should be booked on exchange rate difference accounts. This solution creates problems with some invoices, because it leads to different amounts beeing booked in debit and credit on the debitor/creditor control accounts.

In the example shown here below, we can see that the debitor control account (1100) is booked with 4.266,59 in debit and (32,08 + 4.234,52 = 4.266,60) in credit. And the remaining difference is booked on 5220.

![bildschirmfoto 2015-11-27 um 11 59 33](https://cloud.githubusercontent.com/assets/100664/11439844/61d619e8-94fe-11e5-9d35-9ccedabbd5f0.png)
This booking is reproduced with the reference R-1542 in our common testing database (ledger28).

My theory is that if we would adjust this fix to book the rounding difference on the debitor/creditor control account instead (1100 in our example here above), this issue would be solved.

**Comment by ledger123** [comment]
Hi Sebastian,

I have made this change and tested with the above mentioned transaction. Now difference is correctly being posted to the AR account.

Regards

**Comment by sweitmann** [comment]
Hi Armaghan,

this one is a bit tricky, because whilst solving one issue we have now created a new one. I have added a booking called R-1542-NEW to show the difference. R-1542 was booked before the fix and R-1542-NEW after. As you can see below the new fix now also books the complete exchange rate difference to AR account.

![bildschirmfoto 2015-12-17 um 15 22 26](https://cloud.githubusercontent.com/assets/100664/11871780/07c6214e-a4d2-11e5-9e18-22519db51a47.png)

**Comment by ledger123** [comment]
Hi Sebastian,

I looked into the code and I am looking for the clue when we detect the difference is due to rounding problem or real exchange rate difference. I let you know when I find this and update the code.

Regards

**Comment by sweitmann** [comment]
Hi Armaghan, 

not sure about how the calculation works here, but in the transaction above it looks as if the code already divides the total difference into two separate amounts, namely

a.) 0,01 and
b.) 576,03

Perhaps we can find a way to detect the difference between the rounding amount and the exchange rate amount using the same code that divides the total difference into these two separate amounts?

Regards

**Comment by ledger123** [comment]
Hi Sebastian,

A fix pushed to github.

The problem is that both accounts are booked in gain/loss in the *same* loop so it become impossible to detect when to use AR account and when to use gain/loss account.

Now what I have done is I am selecting AR account when amount is from 0.00 to 0.09 and gain/loss account otherwise. This is not the most elegent solution but it seems to work.

Kindly test it and let me know. If it does not sorts out the problem then we shall spend time again to find what can be done.

Regards

**Comment by sweitmann** [comment]
Hi Armaghan, 

I have tested it and found some strange behaviour:

If you login to our demo (app.myled...) and search the journal for R-1543 you will see the following booking on your screen:

![bildschirmfoto 2016-01-15 um 16 03 42](https://cloud.githubusercontent.com/assets/100664/12356290/1ca25380-bba2-11e5-8c39-6705f4ced970.png)

Now open that booking and re-post it. Once you have done that you will see the following on your screen (checkout debit and credit totals):

![bildschirmfoto 2016-01-15 um 16 03 57](https://cloud.githubusercontent.com/assets/100664/12356317/41e7bc34-bba2-11e5-9d39-0e12c36e8140.png)

If you go back to the journal and search 1543 again it will show the correct totals again.

Any ideas?

Regards
Sebastian

**Comment by ledger123** [comment]
Hi Sebastian,

This has been fixed and now you get correct report after posting. This was due to missing fx_transaction variable.

Regards

**Comment by sweitmann** [comment]
Hi Armaghan,

Tested. Fantastic work, thanks a million. Everything looks great now. Closing this ticket.

Regards
