### ISSUE TITLE
Credit Note shows positive instead of negative

### ISSUE THREAD

**Issue by sweitmann** [ledger123/runmyaccounts#311]
Hi Armaghan, 

If you create an 'AR--Credit Note' and then look for it in 'Cash--Receipt' it will show up as a positive amount instead of negative. And if you book it using the 'Cash--Receipt' module the payment goes in the wrong direction. 

If instead you look for it in 'Cash--Receipt**s**' it will show correctly as negative amount. And if you book it using the 'Cash--Receipt**s**' module everything works fine. 

So this bug is only in 'Cash-Receipt' module. 

Regards

**Comment by phkroll** [comment]
merged to dev
