### ISSUE TITLE
Export (blank) Projekt Transactions

### ISSUE THREAD

**Issue by sweitmann** [ledger123/runmyaccounts#316]
Hi Armaghan, 

When we use 'System--Projekt Erfolgsrechnung' to export the project transactions to .csv file, the (blank) project transactions are not exported.

![Screenshot from 2022-05-11 12-43-37](https://user-images.githubusercontent.com/100664/167834951-02dd796a-d4b1-485e-8287-0bde7288c777.png)

It would be great if we could add those to the .csv export, so that they are also included. 

Regards

**Comment by ledger123** [comment]
Hi Sebastian,

This was a minor issue and fixed and pushed in the commit linked to the ticket.

Regards

**Comment by phkroll** [comment]
Merged the bracnh tod evelop.
