### ISSUE TITLE
Add GL Transaction - Line Tax - Input Screen Adjustments

### ISSUE THREAD

**Issue by sweitmann** [ledger123/runmyaccounts#325]
Hi Armaghan, 

As discussed on Nextcloud we would like to make some adjustments to the line tax 'General Ledger--Add Transaction' input screen. 

The first adjustment would be to simplify the entry screen by removing the Memo/ Source and Project fields and adding a checkbox, so that second rows with Memo/ Source and Project fields are only displayed if the checkbox is marked. The same way as this is done in for example the 'AR--Sales Invoice' input screen:

<img width="1178" alt="Bildschirmfoto 2022-06-14 um 11 03 23" src="https://user-images.githubusercontent.com/100664/173541859-19381a16-f7ae-46ed-ab1b-a3d07bfd898f.png">
<img width="1183" alt="Bildschirmfoto 2022-06-14 um 11 07 16" src="https://user-images.githubusercontent.com/100664/173541978-97785234-eb55-4dc5-9629-69443770b11d.png">

Regards

**Comment by ledger123** [comment]
Hi Sebastian,

This change has been made and pushed to git hub in 325_ branch. 

You can also test on our common server where this branch is current branch.

Regards

**Comment by sweitmann** [comment]
Hi Armaghan, 

Amazing! Wonderful how nice and clean the input screen has become. I'm impressed how fast you could solve this. 

Next step: I have not quite figured out when the project dropdown occurs and when it doesn't, I just know that sometimes it does and sometimes it doesn't. Could you please check the code and see if you can see the logic and let me know why it doesn't always appear when I mark the checkbox in a single row?

![Bildschirmfoto 2022-06-15 um 13 43 18](https://user-images.githubusercontent.com/100664/173819919-56639fb8-aec7-4e74-8b25-7cdf0bb1229f.png)

And if it's not too much hassle, can it be aligned with the Credit entry field above?

Regards

**Comment by sweitmann** [comment]
Update: I just figured it out and it makes sense. If you don't enter anything in Debit or Credit fields and update, the project field will appear. If you enter a number in Debit or Credit and then update, it will not appear. This logic is fine and thus no need for further action in regard to the projects dropdown, thanks. 

If you could just check the alignment that would be great. 

Regards

**Comment by ledger123** [comment]
Hi Sebastian,

Alignment is corrected by moving the project input to the correct column layout. Kindly have a look on our server and then I shall commit the change.

Regards

**Comment by sweitmann** [comment]
Hi Armaghan, 

Thanks, looks great. And could you please also realign the "Tax Amount" field as discussed yesterday? That would be fantastic, thank you. 

![Bildschirmfoto 2022-06-17 um 11 18 09](https://user-images.githubusercontent.com/100664/174269010-0e3b821d-9107-4409-8a15-57f470dd4fa8.png)

Regards

**Comment by sweitmann** [comment]
Hi Armaghan,
