### ISSUE TITLE
SQL-Ledger REST API Project Revival 

### ISSUE THREAD

**Issue by sweitmann** [ledger123/runmyaccounts#326]
Hi Armaghan, 

As discussed we would like to revive our SQL-Ledger REST API Project:
http://www.sql-ledger-network.com/dokuwiki/doku.php?id=rest_api_manual

To start with we would like to create a new REST API for GL entry.

How should we proceed? Is there any further information that you need from my side?

Regards

**Comment by ledger123** [comment]
Hi Sebastian,

API code is updated for your testing. Let me know if any assistance is needed.

Regards

**Comment by sweitmann** [comment]
This project has been taken over by Hashim: 
https://devforum.ledger123.com/index.php?id=42
