### ISSUE TITLE
*** Add name & city and ? to 'Projects--Add Project' customer dropdown 

### ISSUE THREAD

**Issue by sweitmann** [ledger123/runmyaccounts#33]
In for example 'AR--Add Transaction', as shown below, we can also see the customer name and city in the dropdown. And next to the dropdown we also have the "?"-link to customer master data.

![bildschirmfoto 2015-12-11 um 13 58 23](https://cloud.githubusercontent.com/assets/100664/11744288/50495e76-a00f-11e5-80da-d435ff2a1798.png)

It would be great to have the same information and "?"-link when adding a project under 'Projects--Add Project'.

![bildschirmfoto 2015-12-11 um 13 55 28](https://cloud.githubusercontent.com/assets/100664/11744227/e6af1ae6-a00e-11e5-8443-6883b53539dd.png)

Regards

**Comment by ledger123** [comment]
This has been added.

Regards

**Comment by sweitmann** [comment]
Thanks Armaghan. Looks great. Could you please just also add the small arrow (?) next to the drop-down menu that links to the "Edit Customer" screen? 

Regards

**Comment by ledger123** [comment]
Hi Sebastian,

It is already added but is visible only on edit project screen. Can you confirm this?

Regards

**Comment by sweitmann** [comment]
Hi Armaghan,

you are right and I was too fast in writing. Tested and everything works fine. Thank you Armaghan! Closing this ticket now.

Regards
