### ISSUE TITLE
Option to unselect credits in 'AR--Reports--Reminder'

### ISSUE THREAD

**Issue by sweitmann** [ledger123/runmyaccounts#34]
Today, Credit Notes and Credit Invoices are included in the 'AR--Reports--Reminder' report. 

![001](https://cloud.githubusercontent.com/assets/100664/11912834/fcfcbad2-a64f-11e5-8ad5-92ff08150185.png)

There is now a request to be able to exclude credit transactions from this report. Perhaps adding a simple check-box in the search screen would be the best solution?

![002](https://cloud.githubusercontent.com/assets/100664/11912857/9fcc509c-a650-11e5-9a56-69fd89b0cf54.png)

**Comment by ledger123** [comment]
Hi Sebastian,

This has been added.

Regards

**Comment by sweitmann** [comment]
Hi Armaghan,

Works perfect, thanks. Closing this ticket now.

Regards
