### ISSUE TITLE
Email-Address Valiation

### ISSUE THREAD

**Issue by sweitmann** [ledger123/runmyaccounts#35]
Since there is currently no email address validation feature in SQL-Ledger,  today it's possible to send pdf documents from SQL-Ledger to incorrect email addresses such as "erroremail.address@com". 

![004](https://cloud.githubusercontent.com/assets/100664/11912913/9b4f8898-a652-11e5-8a65-96e63f378c44.png)

And when such incorrect emails are sent from SQL-Ledger they are only returned to the email address of the server admin, not to the email address of the user who sent the mail.

![005](https://cloud.githubusercontent.com/assets/100664/11912915/ab27bf06-a652-11e5-9518-5087ac4adc6d.png)

Would it be possible to implement a basic email address validation and have the returned mails sent not only to the server admin, but also to the user who sent the mail?

Regards
Sebastian

**Comment by ledger123** [comment]
Hi Sebastian,

1. There is a Perl module http://search.cpan.org/~rjbs/Email-Valid-1.198/ which I use for validation in my scripts. Should I add it for validation? This is the most robust validation. We can also do validation with our own code but that will not be very comprehensive. There is not downside in using this module and it installs quickly with cpanm command or something else.

2. Email is returned to what is called 'envelop return address' and is specified with '-f' parameter to sendmail. I had made this change many years ago and I can still find it in the code (line 1700 of bin/mozilla/io.pl) and I tested it on our demo server and it seems to be working. See the screen shot.

All you need to set is just specify an email address in Preferences for that user.
![return address](https://cloud.githubusercontent.com/assets/13597/12165091/be0ccd48-b53c-11e5-872f-60f5484bcba4.png)

Regards

**Comment by sweitmann** [comment]
Hi Armaghan,

yes, please add the mentioned Perl module. In Debian it is called  "libemail-valid-perl". 

Regards

**Comment by ledger123** [comment]
Hi Sebastian,

This has been added.

Regards

**Comment by sweitmann** [comment]
Hi Armaghan,

I wasn't able to install the Net::LibIDN module, so I temporarliy excluded this feature on in bin/mozilla/io.pl on my local server.

Will look into this matter again once I have succeeded in installing the missing perl modules. 

Regards

**Comment by nsamuelsson** [comment]
Hi Armaghan,

I think a simple regex check would be sufficient in this case.

kind regards
Nils

**Comment by ledger123** [comment]
Hi Nils,

I have updated code with a regular expression check. (Source: http://www.perlmonks.org/index.pl?node_id=125298)

I have done some basic testing and it seems to be working.

Regards

**Comment by ledger123** [comment]
Please note that I have created develop2 branch for all new changes as I and Sebastian are using develop1 branch to build and test datev export script which may take few days.

Regards

**Comment by sweitmann** [comment]
Tested. Perfect. Solved. Thanks Armaghan! Closing this ticket now.

Regards

**Comment by sweitmann** [comment]
Hi Armaghan,

Yes, I had also noticed this one when trying to print, but never got down to updating the ticket. Thanks for solving it so smoothly.

Regards
