### ISSUE TITLE
QR Variables needed for reminders as well.

### ISSUE THREAD

**Issue by phkroll** [ledger123/runmyaccounts#352]
QR Variables currently only exist in the invoice module and are used there for latex creation.
But we would need them in the reminder as well.

Some I managed to add myself, but others I’m completly lost and don’t get how to add them or way they work for invoice but not for reminders, even if it looks to me that I have 1 property with the same name on both sides, the result in the end is different

This is what was tried:
![Bildschirmfoto 2022-10-14 um 10 12 27](https://user-images.githubusercontent.com/5967878/195797134-8b883848-b728-417a-b8ea-ae753ea96ec8.png)
![Bildschirmfoto 2022-10-14 um 10 12 38](https://user-images.githubusercontent.com/5967878/195797142-7ab0afdb-476a-4c46-bf5d-7a20c910e5ae.png)
![Bildschirmfoto 2022-10-14 um 10 12 45](https://user-images.githubusercontent.com/5967878/195797144-98f20246-3d72-4263-b0ea-3fb1e721f80c.png)

Following is the output:

[1664197285_remittance_voucher_R1000 (1).pdf](https://github.com/ledger123/runmyaccounts/files/9783868/1664197285_remittance_voucher_R1000.1.pdf)
[1664197294_reminder3 (1).pdf](https://github.com/ledger123/runmyaccounts/files/9783869/1664197294_reminder3.1.pdf)

you can see, till QR-invdescription: things do match, afterwards things change.
QR-invdescriptionqr1: it looks to me, like this value is selected from bank in both modules, but for some reason, only reminder has the value from DB, while the invoice doesn’t but is empty instead. Therefor ofc the following output in QR-invdescriptionqr & QR-invdescriptionqr2 change. So in theory, I just could use some other variable but I’m not sure if this rlly would be correct or if I’m missing something.
QR-companyaddress1qr for some reason has a different value from settings->companyaddress.
while the rest of those company address stuff is empty.
QR-swicotaxbaseqr & QR-swicotaxqr I’m not able to get into the reminder.
QR-invdateqr is for some reason different, even if above in Rechnungsdatum both hold the same value, but for somereason, below working with the same variables doesn’t bring me the same output.
QR-strdbkginf & QR-strdbkginfqr & QR-strdbkginfline1qr & QR-strdbkginfline2qr I’m have to select some more infromation from DB I guess, but not sure about it. (edited)

**Comment by ledger123** [comment]
Right. I go through code and check.
