### ISSUE TITLE
Line-Tax Number Format (1.000,00) bug

### ISSUE THREAD

**Issue by sweitmann** [ledger123/runmyaccounts#367]
Hi Armaghan, 

When I book this transaction in demo@ledger28 with number format (1.000,00):

![Bildschirmfoto 2023-02-21 um 17 24 11](https://user-images.githubusercontent.com/100664/220402232-71ec6701-03e0-4265-844c-005e07adce5f.png)

It comes out like this which causes unbalanced journals:

![Bildschirmfoto 2023-02-21 um 17 26 10](https://user-images.githubusercontent.com/100664/220402680-c67e6439-cc5f-45bc-9d15-fb6f8178b95f.png)

Regards

**Comment by sweitmann** [comment]
Hi Armaghan, 

Thanks for looking into this. I tested your fix and it sorts out the issue mentioned above, but in the 'General Ledger--Search' list of transactions this booking still appears with the incorrect numbers.

![Bildschirmfoto 2023-03-14 um 16 39 15](https://user-images.githubusercontent.com/100664/225055287-20079850-2543-4f64-864c-71ed30e206a2.png)
Checkout "test3" booking here above in 'General Ledger--Search' view versus "test3" booking opened here below. 

![Bildschirmfoto 2023-03-14 um 16 37 58](https://user-images.githubusercontent.com/100664/225056146-50abf56f-f8b5-482c-8d30-99cd64696d86.png)

It seems that now the correct numbers are shown when I open the transaction, but the numbers in acc_trans are still incorrect, because I still have unbalanced journals. 

Any ideas why this could be?

Regards

**Comment by ledger123** [comment]
![2023-03-15_11-24](https://user-images.githubusercontent.com/13597/225224331-c45f46b9-aed7-4a06-bf77-b51f627e6ded.png)

Hi Sebastian, good morning.

This seems to be working perfectly for the same transaction. I just entered the reference number and clicked searched and then posted and displayed again and all seems ok.

Which steps you take which cause this?

**Comment by sweitmann** [comment]
Hi Armaghan, 

Thank you for looking into this. Perhaps re-posting an existing transaction is not enough? Please try creating a new line tax transaction in GL instead. I just did it on your server and I get the same error there. 

This is the entry I made and what you see when you open the booking GL-012 on your server:
![Bildschirmfoto 2023-03-15 um 11 39 13](https://user-images.githubusercontent.com/100664/225285190-8f2bb515-d3d7-42d7-9e4a-8cd04f04ef41.png)

But this is what the booking looks like in General Ledger on your server:
![Bildschirmfoto 2023-03-15 um 11 39 25](https://user-images.githubusercontent.com/100664/225285307-75215e7f-62d2-417e-98d9-62ccdd759b85.png)

Regards
