### ISSUE TITLE
Number Format issue

### ISSUE THREAD

**Issue by sweitmann** [ledger123/runmyaccounts#37]
If enter the amount 30,01 in 'AR--Add transaction' when I use the German number format 1.000,00 as shown here below...

![bildschirmfoto 2015-12-30 um 09 49 10](https://cloud.githubusercontent.com/assets/100664/12048398/2e033b22-aedb-11e5-88b6-da6bd98f447a.png)
...and then press 'Update', I get the following amount instead:

![bildschirmfoto 2015-12-30 um 09 49 27](https://cloud.githubusercontent.com/assets/100664/12048411/47899064-aedb-11e5-92e7-4df9e51b7713.png)

Any ideas?

Regards

**Comment by ledger123** [comment]
Hi Sebastian,

This has been fixed.

Regards

**Comment by sweitmann** [comment]
Hi Armaghan,

Solved. Thanks! I will close this ticket now.

Regards
