### ISSUE TITLE
Revolut fee currently not considered

### ISSUE THREAD

**Issue by sweitmann** [ledger123/runmyaccounts#388]
Hi Armaghan, 

Sometimes the Revolut transactions contain a "fee" that is then booked off the account together with the "amount", but our import feature doesn't consider this fee, so the total balance on the account then goes out of sync. 

![Bildschirmfoto 2023-07-15 um 17 18 00](https://github.com/ledger123/runmyaccounts/assets/100664/20956807-c6b8-4c1e-aa17-916851b0b871)

Our import feature only books the "amount":

![Bildschirmfoto 2023-07-15 um 17 20 53](https://github.com/ledger123/runmyaccounts/assets/100664/cdc6cc5f-aff4-46aa-bf3d-4090464dab58)

Whils banks books "amount" + "fee":

![Bildschirmfoto 2023-07-15 um 17 22 33](https://github.com/ledger123/runmyaccounts/assets/100664/cb7e4c85-4854-45ec-b031-7eb59b701769)

It would be great if you could adjust the import script accordingly to also consider the fee. Thank you!

Regards

**Comment by sweitmann** [comment]
Hi Armaghan, 

Wonderful, thank you! Please release to rmac.

Regards

**Comment by ledger123** [comment]
Hi Sebastian,

This code is already in rmac.

Regards

**Comment by sweitmann** [comment]
Hi Armaghan, 

You are right, as always. Confirmed, thus closing this ticket now. Thank you!

Regards
