### ISSUE TITLE
Ask for confirmation before closing browser tab or window

### ISSUE THREAD

**Issue by sweitmann** [ledger123/runmyaccounts#39]
Hi Armaghan,

this is a feature that many users request:

http://stackoverflow.com/questions/10311341/confirmation-before-closing-of-tab-browser

Is it possible to implement this feature in SQL-Ledger?

Regards

**Comment by ledger123** [comment]
Hi Sebastian,

I tried to do it with the code snippet in above link but then it started asking for confirmation on every page change; for example after every 'continue', 'post' etc. Not something desirable.

I then searched for any other possibility but have not found yet. We keep this ticket open and I shall update after some more research.

Regards

**Comment by sweitmann** [comment]
Hi Armaghan,

Thanks. Ok, let's leave it open for the time being. 

Regards

**Comment by nsamuelsson** [comment]
Hi Armaghan,

We could start with a simple thing. When creating a ar-invoice or ar-booking, the script is added to the window. The script it self checks before warning whether the current booking has an id (it is booked). If not, a warning message will be shown.

What do you think about this idea?
Nils

**Comment by sweitmann** [comment]
<img width="740" alt="bildschirmfoto 2016-03-03 um 13 39 08" src="https://cloud.githubusercontent.com/assets/100664/13494574/577f53e0-e145-11e5-9d98-3e5e9c39c7a1.png">
