### ISSUE TITLE
Small bug: Only AR and AP, but not GL transactions prevent currency deletion. 

### ISSUE THREAD

**Issue by sweitmann** [ledger123/runmyaccounts#395]
Hi Armaghan, 

If you book an AR or AP transaction in any currency, sql-ledger will not allow you to delete that currency as long as the bookings remain. But if you book a GL transaction in any currency, sql-ledger will not prevent you from deleting that currency.

We should fix this some time if possible, so I'm taking not of the issue here. Thank you. 

Regards

**Comment by sweitmann** [comment]
Hi Armaghan, 

Awesome! Thank you. Please release to develop and to rmac. 

Regards

**Comment by ledger123** [comment]
Hi Sebastian,

Merged in both branches.

Regards

**Comment by sweitmann** [comment]
Thanks a million, Armaghan! Closing this ticket now.
