### ISSUE TITLE
GL transactions not deleted in GL table

### ISSUE THREAD

**Issue by sweitmann** [ledger123/runmyaccounts#396]
Hi Armaghan, 

As discussed in our call today we have "parents without children" in the GL table, because when you delete a GL transaction it's only deleted in the acc_trans table, but not in the GL table. 

a.) Please correct the code, so that when deleting GL transactions these are also deleted in the GL table
b.) Please add query to Ledger Doctor that will show and allow admin user to delete such "parents without children"

And once you are making changes to Ledger Doctor code, could you please also remove this whole old temporary blank rows fix that is not needed anymore?
![Bildschirmfoto 2023-08-10 um 14 30 25](https://github.com/ledger123/runmyaccounts/assets/100664/995b8340-9ead-494b-85ee-5c9784367c51)
 

Thank you!

Regards

**Comment by sweitmann** [comment]
Hi Armaghan, 

Beautiful, now there are no more "parents without children" when deleting GL transaction. Thank you!

Could you just please add the statement that I need to run on all databases to get rid of the "parents without children" from the time before the fix? 

Regards

**Comment by ledger123** [comment]
Hi Sebastian,

Here is a script you need to run only once on your server. And it shall correct all dbs for good.

https://gist.github.com/ledger123/7110857937836abb7caa4a0324258a25

Regards

**Comment by sweitmann** [comment]
Thank you, Armaghan! Closing this ticket now.
