### ISSUE TITLE
'System-Taxes' list not sorted and account numbers disappear

### ISSUE THREAD

**Issue by sweitmann** [ledger123/runmyaccounts#397]
Hi Armaghan, 

The 'Sytem--Taxes' list is currently not sorted by account number: 
<img width="801" alt="Bildschirmfoto 2023-08-11 um 11 51 49" src="https://github.com/ledger123/runmyaccounts/assets/100664/534067c6-8172-4441-a5ee-0b7dd874a7bc">

And for some reason when updated the account numbers disappear: 
<img width="843" alt="Bildschirmfoto 2023-08-11 um 11 47 52" src="https://github.com/ledger123/runmyaccounts/assets/100664/bf6115cb-7d72-4012-bf08-fa50377f3453">

Would be great if you could sort that out at your next convenience, thank you!

Regards

**Comment by sweitmann** [comment]
Hi Armaghan, 

Looks great, thank you! Just a minor issue left. 

If you run 'System-Taxes' and then click "Update", for some reason the account numbers disappear. Please adjust and then you can release this to develop and rmac. Thank you! 

Regards

**Comment by ledger123** [comment]
Hi Sebastian,

This is fixed. Please have a final look and confirm that all is ok and then I shall merge.

Regards

**Comment by sweitmann** [comment]
Hi Armaghan, 

Tested and confirmed. Now it works beautifully. Please release to rmac and to develop. 

Closing this ticket now. Thank you!

Regards
