### ISSUE TITLE
SQL statement for creating dataset template from existing database 

### ISSUE THREAD

**Issue by sweitmann** [ledger123/runmyaccounts#398]
Hi Armaghan,

Could you please let me know how to formulate the SQL statements for creating a new dataset template from an existing database?

I have been configuring a new database with all the latest changes for the Run my Accounts German market dataset template ([RMADE_DEU_Basiskontenplan-chart.sql](https://github.com/ledger123/runmyaccounts/blob/master/sql/RMADE_DEU_Basiskontenplan-chart.sql)). 

And now I need to create the new SQL statements for that German dataset template, so that whenever we create a new dataset for German market it will also contain my latest changes. 

Regards

**Comment by ledger123** [comment]
Hi Sebastian,

Good evening.

Script to create such a file is linked here: https://gist.github.com/ledger123/4e3651cd11d65c8a7e5bbf4c9fa20936

You just need to copy the script any where on the server where you have the database. Then edit the script and change the database name 'ledger28' to your database and run the script from command line like this:

perl generate_chart_file.pl

It will create the required chart file in the current folder which you can then move any where.

Right now it creates INSERT statements for 3 tables chart, curr, defaults (as per my need) but you can add or remove tables from this list as needed by editing the script.

Let me know if any adjustments are needed.

Regards

**Comment by sweitmann** [comment]
Wonderful, works fantastically! Thank you, Armaghan!
