### ISSUE TITLE
Line Tax Version: Tax account booked with zero although not selected during "Add Transaction"

### ISSUE THREAD

**Issue by sweitmann** [ledger123/runmyaccounts#4]
Although not selected or marked during "Add Transaction" process, tax accounts are booked with zero and appear in 'General Ledger--Report'. 

![bildschirmfoto 2015-08-28 um 09 31 08](https://cloud.githubusercontent.com/assets/100664/9541353/9402dad4-4d67-11e5-8da6-3f3204f050b5.png)

![bildschirmfoto 2015-08-28 um 09 48 44](https://cloud.githubusercontent.com/assets/100664/9541598/0a803038-4d6a-11e5-9731-5690bc57b6bd.png)

**Comment by ledger123** [comment]
Hi Sebastian,

Isn't it the correct behavior for 0 tax report. If some customer or vendor has been marked some tax then it should come into 0 tax report. This was a change done long ago.

And if you don't want the 0 to appear then how we determine which 0 tax to include and which not to include?

Regards

**Comment by sweitmann** [comment]
Hi Armaghan,

correct, but as it works now all tax accounts are booked with zero. To work correctly, only those zero tax accounts that are selected or marked by user during transaction should be booked with zero amount and appear in the general ledger.

Regards
Sebastian

**Comment by ledger123** [comment]
Hi Sebastian,

This has been fixed and pushed. Kindly let me know if everything is ok with this change.

Regards

**Comment by sweitmann** [comment]
Thanks, Armaghan. Looks good. I will close this ticket now.

Regards
