### ISSUE TITLE
* 'AR--Reports--Reminder' Column Sizes and Design

### ISSUE THREAD

**Issue by sweitmann** [ledger123/runmyaccounts#40]
Hi Armaghan,

the column sizes and design in 'AR--Reports--Reminder' would need to be adjusted as follows:

a.) The Customer column is much too wide;
b.) The "Invoice" and "Order" columns are too narrow and should if possible adapt to the lenght of the information they contain;
c.) The language should if possible be selected from the relevant invoice instead of from the customer defaults (this also applies to the languages selected and shown in the 'AR--Reports--AR Aging' report). 

![bildschirmfoto 2016-01-11 um 16 27 51](https://cloud.githubusercontent.com/assets/100664/12237704/5029ca32-b880-11e5-93e0-31ef2e698f00.png)

And would it be possible to add a column stating the calculated amount of days since "Due Date" (= overdue since xx days)?

Regards

**Comment by ledger123** [comment]
Hi Sebastian,

Width issue has been fixed. The language change remains to be done.

Regards

**Comment by sweitmann** [comment]
Hi Armaghan, 

What an improvement! Thanks, it looks much better now. My colleague whos customer requested this will be very happy.

Regards
Sebastian

**Comment by ledger123** [comment]
Hi Sebastian,

Due days from current date - duedate have been added and code pushed to develop1 branch.

Regards

**Comment by sweitmann** [comment]
Hi Armaghan,

Beautiful. Looks great, thanks. Just one more thing: Could you add the possibility to sort by "Due days from current date"? That would immediately solve another feature request that I got the other day.

Regards

**Comment by ledger123** [comment]
Done. Report can be sorted in ASC or DESC by clicking on due days column.

Regards

**Comment by sweitmann** [comment]
Perfect, thanks Armaghan. Closing this ticket now.

Regards
