### ISSUE TITLE
[IBP-399] Customer creation address field behavior

### ISSUE THREAD

**Issue by bohte** [ledger123/runmyaccounts#412]
Hello Armaghan!

Recently we got a request from client to deal with the problem he faced during "customer" creation.
When one tries to create customer with specified address (first field): "Aeschenvorstadt 50 | Postfach" (see screenshot)
![image](https://github.com/ledger123/runmyaccounts/assets/117665763/039f05de-a8e8-42c5-897a-aa965859c15f)
After creation value from address 1 is put as a Post office:
![image](https://github.com/ledger123/runmyaccounts/assets/117665763/7f84aac1-66a7-43c1-8777-58a73fc07e1f)
Yet, if one puts (for example) "Street 51" in address 1 field - then it is saved as address 1 which is expected.

Could You please clarify:
- why this field has such behavior?
- is it expected?
- can it be changed (to be independent from the value)?
- are there any fields with such specific logic that come to your mind?

**Comment by ledger123** [comment]
Hi Bohte,

Yes, this is intended functionality. I had added this when new address columns were added and its purpose was to move the postoffice information to new postoffice column automatically when an existing customer/vendor was edited and saved.

So if there is any thing in address1 and address2 containing 'post', it will be moved to postoffice. Please see the attached screen shot for the code (SL/CT.pm) which does this:

![image](https://github.com/ledger123/runmyaccounts/assets/13597/8dd695b2-5f90-4dc7-98f8-3006cf92b4e3)

We can disable this by removing / commenting out this code.

So far these two fields (address1 and address2) come to my mind where I had implemented this.

Let me know if you need to do any adjustments.

Regards

**Comment by bohte** [comment]
Hello!

Thanks for clarification.
Please, remove this behavior from mentioned fields (address1 and address2).

**Comment by ledger123** [comment]
Merged and pushed to github.

Regards
