### ISSUE TITLE
[IBP-326: LineTax] - Ledger calculations are different from the VAT calculation

### ISSUE THREAD

**Issue by MariaHashimi** [ledger123/runmyaccounts#415]
while testing the LineTax, we have noticed that Ledger calculations are different from the VAT calculations.

 **This means:**
 When a booking is created via Ledger and the user changes the Linetax amount manually (you don't let ledger calculate it) and then save the booking. The tax amounts is recalculated by ledger and is overwritten.

The manually changed amount is stored but not displayed when the booking is opened. In the journal and Linetax report, the changed amount.

This is quite confusing for the accountants/users in their daily workflow and when they have to control the VAT.

Sebastian informed us that you and him have found a solution for that but he did not know if the solution was already implemented by you or not.

**Comment by ledger123** [comment]
Hi Maria,

Good afternoon,

I have pushed a commit to fix this issue. Kindly test and confirm.

Just as a little precaution, please test this thoroughly with all possible scenarios with or without linetax as code for transactions is quite complicated and we need to be sure that all is ok before merging.

Regards

**Comment by MariaHashimi** [comment]
Hi @ledger123,
During the testing we noticed that the VAT-Calculation were displayed in "negative" in the ledger

**Comment by ledger123** [comment]
Hi Maria,

Very surprisingly, I cannot reproduce this error on setup. Can you test this here:

https://app.ledger123.com/rma
user: demo@ledger28
pass: demo

I have enabled the line tax.

Or we can have a quick call and do it together on shared screen.

Regards

**Comment by MariaHashimi** [comment]
Hi @ledger123,

We have tested this once again and noticed that the values are still overwriting the modified values that are coming from docca. We had the case with the attached XML.
[rma-executor.log](https://github.com/ledger123/runmyaccounts/files/14332462/rma-executor.log)

We can also organize a quick meeting to show you this issue

**Comment by ledger123** [comment]
Hi @MariaHashimi ,

The original issue we had was resolved and I had verified it on my server.

Can you please reproduce this new issue on our testing server? I do not have docca setup and cannot reproduce it and also the log will not help.

If everything is working perfectly in sql-ledger then problem is probably at docca end.

And if the issue cannot be reproduced on our test server or cannot be explained in some simple way than we shall discuss it in our meeting with screen sharing if needed.

Regards

**Comment by ledger123** [comment]
Hi @MariaHashimi ,

I have switched the branch. Can you please on our demo server and confirm all is ok now?

Regards

**Comment by MariaHashimi** [comment]
HI @ledger123 ,
Successfully tested on your demo environment - will push this to our INT and close the issue.
Thanks a lot for the fix :)
