### ISSUE TITLE
[IBP-154] - Batch email invoices - Filter "Not sent" is not working

### ISSUE THREAD

**Issue by MariaHashimi** [ledger123/runmyaccounts#418]
We have since a moment an issue where the filter "not sent" is not working in the batch e-mail invoices (https://infoniqa.atlassian.net/browse/IBP-154).

Sebastian told us this issue was fixed wht the following:  https://github.com/ledger123/runmyaccounts/commits/master

We have merged this commit to master, but the support informs us that they still have this issue on PROD clients (Example: Invoice “21.11.2023” on client musterfirma)

The support has tested it on your environment as well and the is issue still appears (please see video that I will send you by e-mail)

**Comment by ledger123** [comment]
Hi Maria,

Good morning.

I just went through the code and discovered that you can only batch email *AR invoices* and not *AR transactions*. The video you have sent is showing an AR transaction and not an invoice.

Here is code segment in SL/BP.pm which limits the list to invoices only:

![image](https://github.com/ledger123/runmyaccounts/assets/13597/662176e7-b4ca-404f-91a7-69e5a187e51a)

Kindly check and confirm that invoices are correctly shown.

Regards

**Comment by MariaHashimi** [comment]
Hi @ledger123,
Philip from the support tested it with AR invoices and they don’t work either. Video attached. 

Uploading Invoices Batch Email.mp4…

**Comment by MariaHashimi** [comment]
Hi @ledger123,
This ticket was successfully tested by our support-team on INT -  Closing the ticket :)
