### ISSUE TITLE
[IBP-410] - SQL-Ledger: wrong automatic rounding

### ISSUE THREAD

**Issue by MariaHashimi** [ledger123/runmyaccounts#420]
Detailed Description: 

https://runmyaccounts.zendesk.com/agent/tickets/51745

If the "VAT included in price" checkbox is selected, the amounts are overwritten by the system. 

The amounts cannot be adjusted manually. In the following example, I have entered the amounts as CHF 110,000 less CHF 30,000. After updating and posting, the amounts are displayed with differences in centimes.

Impact: Rounding differences

Steps to Reproduce:  Create a booking like the example in the screenshot.
![Screenshot Example](https://github.com/ledger123/runmyaccounts/assets/152606672/7fac0a51-4787-486f-8d4f-86d98d11717d)

Affected Components: Invoice Masks

Environment Details: SQL-Ledger

**Comment by ledger123** [comment]
Hi Maria,

Good morning.

I have just created a transaction on my server and all seems to be ok. Can you login to my server and check why I am not able to reproduce it? Transaction reference is 'roundingdiff'.

url: https://ledger123.com/rma/
user: demo@ledger28
pass: demo

![image](https://github.com/ledger123/runmyaccounts/assets/13597/388d39cb-0c6c-4ce6-b273-7f081c0ac24c)

Regards

**Comment by MariaHashimi** [comment]
@ledger123 thanks a lot for your comment, I've asked the support to test this again and give us a quick feedback, will close the ticket if everything looks ok for the support :)

**Comment by MariaHashimi** [comment]
successfully tested by Philipon Armaghan's environment, closing the ticket
