### ISSUE TITLE
[IBP-529] - Chart of accounts - Add parent groups

### ISSUE THREAD

**Issue by MariaHashimi** [ledger123/runmyaccounts#428]
In the new chart of accounts, we need to be able to group the different charts in a parent group. 
Therefore we need to be able to store the parent_id on the chart.

As discussed, the storage of the levels are not needed and we are not going to touch the reporting part.

**Comment by ledger123** [comment]
Hi Maria

Good afternoon.

This task is done and can be tested on my test server. Code has been pushed to the branch starting with 529_ (from IBP-529). Here are screen shots:

![image](https://github.com/ledger123/runmyaccounts/assets/13597/bae1f532-c70f-475a-a945-d56660f754d7)

![image](https://github.com/ledger123/runmyaccounts/assets/13597/573c3e47-f469-4052-80ef-edac89e804a9)

You can do basic testing on my  test server too as I have activated this branch there or download and test on your server.

Regards

**Comment by MariaHashimi** [comment]
Hi @ledger123 
We have tried to test this fix on your server
URL: https://ledger123.com/rma/login.pl

Unfortunately, we (Raphi and I) could not see the parent group, is the test-server the right one?

![2024-01-12_10h10_13](https://github.com/ledger123/runmyaccounts/assets/152606672/b10b0af0-53a1-4d67-ba27-4e6dbd09f11e)

![2024-01-12_10h10_27](https://github.com/ledger123/runmyaccounts/assets/152606672/fa79eaac-a8da-442a-a18f-32729daf2b32)

**Comment by ledger123** [comment]
Hi Maria,

Please check now as I have switched to the respective branch.

Apologies for the confusion.

Regards

**Comment by MariaHashimi** [comment]
Sucessfully tested on the https://app.ledger123.com/rma-maria/ test environment - will close the this issue :)
