### ISSUE TITLE
Add currency exchange rate column to 'Import--Sales Invoices'

### ISSUE THREAD

**Issue by sweitmann** [ledger123/runmyaccounts#43]
Hi Armaghan,

as discussed during our Skype call today, we should add an currency exchange rate column to 'Import--Sales Invoices'

![bildschirmfoto 2016-01-19 um 11 48 46](https://cloud.githubusercontent.com/assets/100664/12416606/ad1e9e70-bea2-11e5-924f-7e444c8283a9.png)

Regards

**Comment by ledger123** [comment]
Hi Sebastian,

This is done and code pushed. 
[sales_invoice.txt](https://github.com/ledger123/runmyaccounts/files/108331/sales_invoice.txt)
I have tested it with the sample file attached to this update.

Regards

**Comment by sweitmann** [comment]
Hi Armaghan,

Tested. Works beautfully. Thanks for your excellent support. Closing this ticket now.

Regards
