### ISSUE TITLE
[IBP-540] - Foreign Exchange Bookings

### ISSUE THREAD

**Issue by MariaHashimi** [ledger123/runmyaccounts#433]
booking shall show both entries and also that it's an fx_adjustment booking

Impact:
Bookings cannot be edited. → Wrong accounting.

**Comment by ledger123** [comment]
Hi Maria,

This has been fixed in the 433_fx_trans_cannot_be_edited branch.

You can test it on our common server. Let me know before testing so that I switch code to the correct branch.

Regards

**Comment by MariaHashimi** [comment]
Hi @ledger123,
Thanks for this information, will inform the support about this and will give you an update as soon as they have tested it.

Just for my understanding, is our common server the following test-server:
url: https://www.ledger123.com/rma/
login: demo@ledger28
pass: demo

**Comment by ledger123** [comment]
Hi Maria,

Just a minor correction to the url:

url: https://app.ledger123.com/rma/
login: ***@***.***
pass: demo

Regards

**Comment by MariaHashimi** [comment]
Hi @ledger123,
Philip from Support informed me he tested this issue with branch 433 and it worked.
So I'm closing it
