### ISSUE TITLE
Zero 'AP--Sales Invoice' error

### ISSUE THREAD

**Issue by sweitmann** [ledger123/runmyaccounts#44]
Hi Armghan,

When booking this transaction...

<img width="1014" alt="bildschirmfoto 2016-02-18 um 18 28 15" src="https://cloud.githubusercontent.com/assets/100664/13152109/c90a9e3a-d66d-11e5-8fd1-9258c826c5d4.png">

...with EUR currency and exchange rate as above, I get the following error message:

<img width="419" alt="bildschirmfoto 2016-02-18 um 18 28 31" src="https://cloud.githubusercontent.com/assets/100664/13152149/f7a0ea56-d66d-11e5-86fd-2bdda14c7e10.png">

Any ideas?

Regards

**Comment by ledger123** [comment]
This has been fixed.

**Comment by sweitmann** [comment]
Hi Armghan,

Wonderful, thanks. Closing this ticket now.

Regards
