### ISSUE TITLE
Taxamount of a GL Booking is calculated wrong

### ISSUE THREAD

**Issue by benboehm** [ledger123/runmyaccounts#445]
When creating a booking:
![image](https://github.com/ledger123/runmyaccounts/assets/56029764/616e7a6a-889b-4a2b-a68f-f9beeea998ff)

And Updating it:
![image](https://github.com/ledger123/runmyaccounts/assets/56029764/130fb078-9294-4d49-a298-3a608a860876)

The resulting booking
![image](https://github.com/ledger123/runmyaccounts/assets/56029764/4c36ed5e-aa39-4785-b589-3b5d7e0209b7)

Has the wrong tax amount (Maybe not wrong, since the expected tax amount is the the same but divided by 100)

**Comment by MariaHashimi** [comment]
Hi @ledger123,

We tested this issue on your serveur and it seems that the issue was not fixed yet, you will send you the recording per chat as it is too big to attach on the comment

**Comment by MariaHashimi** [comment]
successfully tested on INT - Closing the issue
