### ISSUE TITLE
Posting a booking without Updating before behaves differently with linetax

### ISSUE THREAD

**Issue by benboehm** [ledger123/runmyaccounts#446]
Creating a booking with the last line filled behaves different if you either create a booking for a client without linetax or a client with linetax enabled, but the tax inputs not filled and a client that has linetax enabled and the tax inputs are being filled

So when no linetax is enabled, or just not filled, the last line during the creation of a booking is read, and filled into a booking e.g:
![image](https://github.com/ledger123/runmyaccounts/assets/56029764/60fab45f-63cf-42f9-b51c-93878b41c1bb)
(Note: I Updated to remove all the lines, and filled in the last line. This is reproducable by just using postman and recreating the call that is being made (which we usually do, which is why we don't call update))

Result is:
![image](https://github.com/ledger123/runmyaccounts/assets/56029764/f3ae8b4a-6e9e-48c3-8920-61ec7783efbb)

So all the lines I wrote during creation are written

But when I add some kind of linetax:
![image](https://github.com/ledger123/runmyaccounts/assets/56029764/d46b67f0-cc00-474d-b51b-dcd121e2ef1d)

the last line is missing:
![image](https://github.com/ledger123/runmyaccounts/assets/56029764/30fa363f-a1e3-4e11-9444-ae1aa4405199)

It would be great, that it behaves the same way regardless of having linetax or not

**Comment by MariaHashimi** [comment]
successfully tested on INT & your server, closing the ticket
