### ISSUE TITLE
GL - VAT calculation are wrong

### ISSUE THREAD

**Issue by MariaHashimi** [ledger123/runmyaccounts#458]
While testing the LineTax we noticed with Suzana that the VAT-Calculations are not done properly in ledger.
I've tested it on your server and have the same result
You will find the recording in the attachments.

https://github.com/ledger123/runmyaccounts/assets/152606672/6418a4ab-63eb-41ac-a341-b682a9bebd35

**Comment by ledger123** [comment]
Hi Maria,

Tax calculations on GL are always tax inclusive as otherwise transaction will not balance.

So taxable amount = 100/1.081 (when 8.1 is tax percentage) which is 92.51 and tax is 100 - 92.51 = 7.49 as shown in the video.

Can you please check and confirm?

Regards

**Comment by MariaHashimi** [comment]
im really sorry for this confusion, going to close the ticket.
Thanks a lot for your comment :)
