### ISSUE TITLE
Decimalplaces Option for 'System--Abteilung Erfolgsrechnung'

### ISSUE THREAD

**Issue by sweitmann** [ledger123/runmyaccounts#46]
Hi Armaghan,

We have a feature request for a "Decimalplaces" option...
 
![bildschirmfoto 2016-02-18 um 18 55 54](https://cloud.githubusercontent.com/assets/100664/13152805/4c40e45a-d671-11e5-85ba-681052aa4b22.png)

...in the 'System--Abteilung Erfolgsrechnung'

<img width="675" alt="bildschirmfoto 2016-02-18 um 18 43 22" src="https://cloud.githubusercontent.com/assets/100664/13152835/6f5bbd48-d671-11e5-8864-edc4483cf2b0.png">

Regards

**Comment by ledger123** [comment]
This option has been added.

**Comment by sweitmann** [comment]
Hi Armaghan,

Fantastic, thanks for solving. Closing this ticket now.

Regards
