### ISSUE TITLE
AP-/AR-Invoices don't support linetax

### ISSUE THREAD

**Issue by raphaelroos** [ledger123/runmyaccounts#483]
Currently, linetax is not supported for AP-/AR-Invoices in SQL-Ledger. Tax rate can be selected for each line...
![image](https://github.com/ledger123/runmyaccounts/assets/116798460/e111af91-a2ea-4f2a-af89-f2d523c81ec3)

...but sum of each tax rate will be booked in a separate transaction and the fields "taxamount" and "tax_chart_id" are not filled
![image](https://github.com/ledger123/runmyaccounts/assets/116798460/b9dff9e1-8755-4932-a413-79a9fa283a3d)

Is it possible to change this so that taxes will be booked with linetax also for invoices if linetax is enabled?

**Comment by raphaelroos** [comment]
I checked the linetax report of sql ledger for the example above. It seems that tax numbers are wrong here, no?
![image](https://github.com/ledger123/runmyaccounts/assets/116798460/c83e09cc-a742-4635-83c0-b3dbe0bee3b0)

**Comment by ledger123** [comment]
> Currently, linetax is not supported for AP-/AR-Invoices in SQL-Ledger. 
> Is it possible to change this so that taxes will be booked with linetax also for invoices if linetax is enabled?

Hi @raphaelroos,

Line tax cannot be supported for invoice line items because each line item (part, service) can have multiple taxes configured for it. And each tax is also dependent on the selection of tax for that customer or vendor.

Further we can discuss on meeting if needed.

Regards

**Comment by ledger123** [comment]
> I also checked the linetax report of sql ledger for the example above. It seems that tax numbers are wrong here, no? 

Linetax report is quite thoroughly tested so probably it should be ok. But we can do to troubleshoot the reported issue:

Check and confirm if the figures are different in the 'Tax Collected' report than this report? The different between line tax and tax collected report is that linetax report shows all taxes.

Regards

**Comment by raphaelroos** [comment]
Hi @ledger123, 

thanks for your answers. I found a way to handle those non-linetax transactions in our VAT settlement.
About the "wrong" numbers in the linetax report, there was a misunderstanding from my side. So, no further actions are needed. I will close this issue.

Regards,
Raphael
