### ISSUE TITLE
[Support production / IBP-832] - SQL-Ledger - Exchange rate is calculated differently

### ISSUE THREAD

**Issue by MariaHashimi** [ledger123/runmyaccounts#485]
Detailed Description: 

From: https://runmyaccounts.zendesk.com/agent/tickets/54437

Here we have the case that the EUR exchange rate is calculated twice differently with the same amount.

Example:

1) ![Exemple 1](https://github.com/ledger123/runmyaccounts/assets/152606672/114cf890-b72c-4558-90f1-93e5cb266382)

Exchange rate at 01.02.2024: 0.9458 CHF / EUR (https://my.runmyaccounts.com/#/settings/goodform/accounting/currencies/EUR )

EUR 339.05 = CHF 320.67 → exchange rate difference of CHF 18.38.

12871-240208-0002 has an exchange rate difference of CHF 18.38 which is correct.

UBS CH450023023080570960L 11.2023 (4728941-999) has an exchange rate difference of CHF 10.85 which is wrong.

The problem seems to lie here:  ![image-20240327-064611](https://github.com/ledger123/runmyaccounts/assets/152606672/1fa79e2c-6be3-43c6-b078-161a0d03034c)

For the exchange rate difference, the exchange rate of the invoice (0.9680) is taken instead of the exchange rate of the payment (0.9458).

Impact:

Manual adjustments needed from accountant.

Steps to Reproduce: 

Unknown as these bookings were made by the system.

Affected Components:

General ledger.

Steps Taken (if any):

Analysed bookings. There’s also a second example:

12871-231023-0103 vs. 12871-240212-0022

**Comment by ledger123** [comment]
Hi @MariaHashimi ,

I will be grateful if you can reproduce this bug on our demo server at https://app.ledger123.com/rma

Regards

**Comment by MariaHashimi** [comment]
Hi @ledger123,
I've received the following comment from Philip 

> Cannot reproduce on Armaghan’s server. We booked it manually there with the same amounts and fx rates and everything was fine. We assume the root cause lies in the automatic booking from Booka that takes another fx rate than SQL Ledger.

![image-20240606-123421](https://github.com/ledger123/runmyaccounts/assets/152606672/fd9de524-9b68-4187-ad31-d600dd3e42c9)

So I will close this ticket and check with Suzana
