### ISSUE TITLE
Mojo and Config Issues

### ISSUE THREAD

**Issue by benboehm** [ledger123/runmyaccounts#487]
So there is an issue with mojo and our sql-ledger.conf file

firstly
we sometimes comment some values out in the sql-ledger.conf
e.g.:
```
#ip_whitelist = "31.12.51.25";
ip_whitelist = "192.168.1.2,102.168.1.3";
```

now first issue is that in the "normal" ledger we read the second line, but in the mojo part, we don't check if the property we read is commented out or not, we just take the first occurance of ip_whitelist

the second issue is, that if we take the second value
the regex we compare it to is basically just that

so if a user has an ip like 192.168.1.3

we compare it like this:
192.168.1.3 = 192.168.1.2,192.168.1.3

which doesnt work

**Comment by ledger123** [comment]
Hi @benboehm ,

I have fixed both issues.

1. First non-commented line will be used.
2. You can specify multiple ips on a single line. Just make sure to separate every ip with space instead of comma.

Changes commit is attached above to this ticket.

Regards
