### ISSUE TITLE
Feature request: Consolidate multiple sales invoices

### ISSUE THREAD

**Issue by sweitmann** [ledger123/runmyaccounts#49]
Hi Armaghan,

can we add a feature for consolidating sales invoices, just like the one we have for consolidating sales orders?

![bildschirmfoto 2016-02-19 um 11 57 56](https://cloud.githubusercontent.com/assets/100664/13173856/36ae70e6-d700-11e5-86c7-acb6cf1bef14.png)

Regards

**Comment by sql-ledger-network** [comment]
I will re-check the requirements and the reason for this feature request, in order to first exclude the possibility of solving this issue with a work-around solution. Argument: an invoice is a legal document.
