### ISSUE TITLE
Line Tax version: When new Customer is selected, all tax boxes are automatically checked

### ISSUE THREAD

**Issue by sweitmann** [ledger123/runmyaccounts#5]
When a new Customer is selected in 'AR--Add Transasction' and 'AR--Add Credit Note' or when a new Vendor is selected in 'AP--Add Transaction' or 'AP--Add Debit Note', all tax boxes displayed are automatically checked. 

![bildschirmfoto 2015-08-28 um 11 00 42](https://cloud.githubusercontent.com/assets/100664/9542767/1a6b67d8-4d74-11e5-9538-60ea0dd5f977.png)

Since we have decided to work only with line tax in the Line Tax version, the total tax boxes can all be deactivated and should only show the total tax calculated for each tax account in the single lines above. 

![bildschirmfoto 2015-08-28 um 11 14 53](https://cloud.githubusercontent.com/assets/100664/9543072/1b8ec536-4d76-11e5-89c8-436988ff2544.png)

**Comment by ledger123** [comment]
Hi Sebastian,

This is also fixed. Have a look and confirm.

Regards

**Comment by sweitmann** [comment]
Hi Armaghan,

awesome, thanks. Closing this ticket now.

Regards
Sebastian

Regards
Sebastian
