### ISSUE TITLE
View all account transaction totals in local currency

### ISSUE THREAD

**Issue by sweitmann** [ledger123/runmyaccounts#50]
Hi Armghan,

This is a difficult one to explain in writing, so I will explain it to you in person next week instead.

Regards

**Comment by sql-ledger-network** [comment]
Definition: To summarize foreign exchange rate difference transactions into one line only. As discussed during our meeting in Lahore.

**Comment by ledger123** [comment]
We have made some database changes for Datev export processing. Once that issue is closed, we shall be able to create this report quickly.
