### ISSUE TITLE
IBP-767 - customer address

### ISSUE THREAD

**Issue by bohte** [ledger123/runmyaccounts#503]
Recently we've got new defect ticket related to behavior of customer create/update form.
In the reported scenario when user tries to update address of customer something unexpected happens with field values and order of values is changed after save:

1) Let's say i have a customer with such data:
![image](https://github.com/ledger123/runmyaccounts/assets/117665763/5526e23e-0f4c-47cc-933d-fc19624fb9ef)

2) i want to switch address lines to have it like:
![image](https://github.com/ledger123/runmyaccounts/assets/117665763/d274e447-5ffa-4eac-be26-353558680e73)

3) i press 'save' button but when i open the same customer again - order is not changed

**Comment by MariaHashimi** [comment]
Philip successfully tested this ticket on DEV 
his comment on the jira ticket: Tested on dev with client 31ea2ef08ec344b2aa6789a4dd50c0b0 successfully. See video attached.

@ledger123  we can close this issue :) I can't do it as I have not issue
