### ISSUE TITLE
IBP-1136 - Remove chart currency logic from SQL-Ledger

### ISSUE THREAD

**Issue by bohte** [ledger123/runmyaccounts#544]
Hi,

We have decided to change the approach of handling currencies in context of chart of accounts.
Therefore, please, remove all the logic related to 'curr' column in "chart" table (both backend and frontend).

Please, use this branch to introduce all the changes:
[IBP-1134-Foreign-currencies-Bookings-Migrate-currency-assignment](https://github.com/ledger123/runmyaccounts/tree/IBP-1134-Foreign-currencies-Bookings-Migrate-currency-assignment)
Also, be aware that I have already introduced drop for the column in the script **Pg-upgrade-2.8.36-2.8.37.sql**

**Comment by ledger123** [comment]
Hi, 
This is done in the above mentioned branch and commit is also linked to this ticket above.

I have tested on my test data and all seems ok. My test server is also on this branch if you want to test it there.

Regards

**Comment by bohte** [comment]
Hi,

Great, thanks.
Initial testing went fine.

We will proceed with implementation and testing on our side and let you know about the result.

**Comment by bohte** [comment]
So far tests went good. Closing the issue.

Thanks!

**Comment by bohte** [comment]
The issue with chart of account page was found and fixed
