### ISSUE TITLE
[IBP-1212] Issue with GL transactions with foreign currency

### ISSUE THREAD

**Issue by TomaszKrolczyk** [ledger123/runmyaccounts#554]
Hello,

German users of our system are facing issues with GL transactions with foreign currency.
I analyzed the problem and it looks like we have two rather small issues that combined make a real mess with the numbers:
1) When we edit the GL transaction and manually modify the exchange rate, after "Post as new" the buy value overwrites the value of the exchange rate
2) When it happens, the value read from the database is not formatted in line with users' preferences. If an exchange rate is stored as 1.0345 and a user has the following formatting: dot as a thousand separator and a comma as a decimal, the exchange rate is parsed in a wrong way which implicits wrong calculations. 

**Better description & steps to reproduce:**
1. Add new GL transaction with foreign currency and manually modify the exchange rate
![image](https://github.com/user-attachments/assets/f13e75a9-d336-46b6-8e56-09acf96a17db)
2. Find the transaction. At this moment everything looks good. Post this transaction as new. (I changed the reference for easier identification)
![image](https://github.com/user-attachments/assets/c684e023-0d71-4398-b92d-8c9bad33e4f1)
3. Find the new one. The exchange rate was overwritten. **This is the first issue**
![image](https://github.com/user-attachments/assets/4bbaf8f7-39f1-4eaa-b5ff-c19ef96c4451)
4. Now let's find a user with the following number formatting:
![image](https://github.com/user-attachments/assets/cc076293-df7e-43b7-b47f-970ea7c2dde5)
5. This is how he sees the transaction
![image](https://github.com/user-attachments/assets/fb1286e1-0c18-4bf6-ac7f-c43a65b9d499)
6. Now let's try to post another transaction as new (using this user). I changed the reference and exchange rate
![image](https://github.com/user-attachments/assets/101d592e-e8f5-4ee9-bc0d-133730868bcb)
7. And this is **the second issue**. Numbers are crazy because of the huge exchange rate.
![image](https://github.com/user-attachments/assets/84b42872-467c-4589-8006-c0898ac7ddec)
![image](https://github.com/user-attachments/assets/f3992bc3-8598-4179-b359-53045ea2e0e3)

I dig a little into the code and I think the issue is in **bin\mozilla\gl.pl** in **update** function:
![image](https://github.com/user-attachments/assets/8aba2c7e-6fb9-491e-bc5d-62c232a09ad0)
The exchange rate is read from the database (the original put by a user is overwritten - the first issue) but it is not formatted with user settings. When a user has formatting with dots as thousands separator a new value is wrongly parsed as a dot is used in the database as a decimal separator.
I managed to solve the issue locally by adding the lines that are commented out in the screen above but I am not aware of the possible implications of such a change so it would be great if someone experienced with the system could take a look at it.
![image](https://github.com/user-attachments/assets/4b23e7d3-82ae-4444-a173-6985be8620c1)
And the result (the value of exchange rate is still overwritten but calculations are ok):
![image](https://github.com/user-attachments/assets/9e857392-9636-4d5a-b70b-110fecf5e77c)
![image](https://github.com/user-attachments/assets/e2f7e289-bea8-4528-9572-8a08ff87d4dc)

Thank you in advance for looking into that

**Comment by ledger123** [comment]
Hi @TomaszKrolczyk , issue is resolved and commit is attached to the script in its branch.

Thanks for such detailed issue reporting. This helped resolve the issue quickly.

Please test and confirm all is ok. I am here all day for quick resolution if you still find some problem.

Regards

**Comment by ledger123** [comment]
Hi,

I have fixed the issue and set the precision without any number just like it is in other places.

Regards

**Comment by TomaszKrolczyk** [comment]
I have a confirmation for German users that the issue is solved. Thank you for your quick response and fix.
The issue can be closed.
