### ISSUE TITLE
Clear code from SQL-Injection vunerability

### ISSUE THREAD

**Issue by sweitmann** [ledger123/runmyaccounts#57]
Hi Armaghan,

just adding this ticket for tracking purposes. Everything else as discussed over Slack.

Regards,

**Comment by sweitmann** [comment]
Hi Armaghan,

I just saw that we have been instructed to resolve this latest by the 23.03.2016.

Regards,

**Comment by ledger123** [comment]
Hi Sebastian,

I really hope it shall be done even before than this. For me it is an easier assignment than searching for bugs. :)

Regards

**Comment by ledger123** [comment]
Hi Nils,

Just for the record here is a basic checklist I am using as I go through the code line by line.

1. All id's should be multiplied by 1 before concatenating.
2. All text columns should be inserted/updated with dbh->quote function.
3. All variable names for column or table names should be validated for legal values before concatenating within SQL. (like $form->{db} should have only 'vendor' or 'customer' as its values before use in any SQL statement)

If you can think of any other possibility, let me know to add to this list.

Regards

**Comment by sweitmann** [comment]
Thanks, Armaghan! Nils has told me to close this ticket now.
