### ISSUE TITLE
Incorrect paid amount shown in transaction report

### ISSUE THREAD

**Issue by ledger123** [ledger123/runmyaccounts#58]
This occurs when the invoice amount and paid amount difference is exactly that of tax for that invoice.

**Comment by ledger123** [comment]
This has been fixed.

**Comment by sweitmann** [comment]
Hi Armaghan,

Thanks. Tested and confirmed. Closing this ticket now.

Regards

**Comment by sweitmann** [comment]
Actually, you will have to close this one, since you opened it :)
