### ISSUE TITLE
Postings - Memo dissapeas when LineTax is enabled

### ISSUE THREAD

**Issue by MariaHashimi** [ledger123/runmyaccounts#580]
HI @ledger123,

We have noticed that the "memo" field in the Ledger postings disappears when the function linetax is activated.

Could we please have the memo field in the postings when linetax is also activated?

When LineTax is not activated, the users can see the field "memo" in the postings:
![Posting_LineTax not activated](https://github.com/user-attachments/assets/621c97a9-517a-4c40-95a5-d3dccf7c2b8b)

But when LineTax is activated, the users cannot see the "memo" field anymore in the postings:
![Posting_LineTax activated](https://github.com/user-attachments/assets/b424a840-500d-48f6-8b41-652897aaa9f0)

**Comment by ledger123** [comment]
Hi @MariaHashimi ,

Please click on checkbox next to account and you will see the memo and source fields. Please also note that heading of first column is changed from 'Account' to 'Account / Memo / Source' when line tax is enabled. Here is screen shot:

![image](https://github.com/user-attachments/assets/680b45f4-1766-4b0c-bbfa-8513979f5407)

Hope this explanation addresses this issue.

Regards

**Comment by MariaHashimi** [comment]
Hi @ledger123 ,

Thanks a lot for this explanation, I've also noticed that I needed to update the booking in order fo tind the fields.

Will close the ticket :) 

See you soon and best regards,
Maria
