### ISSUE TITLE
DONE: Unbalanced journals during import

### ISSUE THREAD

**Issue by sweitmann** [ledger123/runmyaccounts#59]
Hi Armaghan,

when you import accounting data using the "Import--General Ledger" function, there doesn't seem to be any check for unbalanced journals:

![001](https://cloud.githubusercontent.com/assets/100664/14431772/7d6050c4-0007-11e6-8ca4-553c5fa63428.png)

If possible, we should not allow such unbalanced journals to be imported. Unbalanced journals should instead produce an error message like "Error! Out of balance transaction!"

**Comment by ledger123** [comment]
Hi Sebastian,

The unbalanced check is already there. I just tested and I got the error. When totals are not equal, 'Import' button is not shown and error is shown.

Can you reconfirm as I just tested it again now.

Regards

**Comment by sweitmann** [comment]
Checkout https://github.com/ledger123/runmyaccounts/issues/67
