### ISSUE TITLE
Line Tax version: 'General Ledger--Add Transaction' TAB jumps and VAT total amount

### ISSUE THREAD

**Issue by sweitmann** [ledger123/runmyaccounts#6]
I picked up this issue from ledger123/ledger123 (https://github.com/ledger123/ledger123/issues/3).

There were two small issues left: 

a.) When I use the tab key the cursor jumps from Account -> Memo -> Source -> Debit -> Credit etc. This means it jumps between the lines. Would it be possible to make it jump from Account -> Debit -> Credit -> Tax Included -> Tax Amount -> Memo -> Source -> Project -> Account ... instead?

2.) We could save some more width if we moved the total tax amount below the tax amount fields instead? Can this be done easily? 

![bildschirmfoto 2015-08-28 um 12 02 02](https://cloud.githubusercontent.com/assets/100664/9543865/a3aa8ce2-4d7c-11e5-8f86-397fc604e813.png)

You wrote that this had been done and pushed to github, but in my develop branch these two issues still exist. Any ideas?

**Comment by ledger123** [comment]
This is done and code is pushed to github.

Regards

**Comment by sweitmann** [comment]
Thanks, Armaghan. I will close this ticket now.

Regards
