### ISSUE TITLE
'Tools--Batch--Print Sales Invoice' minor issue

### ISSUE THREAD

**Issue by sweitmann** [ledger123/runmyaccounts#62]
Hi Armaghan,

When you print a Sales Invoice containing the "+" character to queue using the 'Tools--Batch--Print Sales Invoices' and then download the zip-file with the 'Tools--Batch--Queue Sales Invoices', for some strange reason the "+" character is converted to "'&amp;#43;" instead.

a.) Sales Invoice content:
<img width="357" alt="bildschirmfoto 2016-04-28 um 17 26 55" src="https://cloud.githubusercontent.com/assets/100664/14891418/e3ea3910-0d66-11e6-918d-f34a1b0f1494.png">

b.) Normal pdf print to screen content:
<img width="229" alt="bildschirmfoto 2016-04-28 um 17 27 24" src="https://cloud.githubusercontent.com/assets/100664/14891429/ef39a210-0d66-11e6-87e7-eca456b6b9fa.png">

c.) Strange 'Tools--Batch--Queue Sales Invoices' Zip-file pdf content:
<img width="299" alt="bildschirmfoto 2016-04-28 um 17 29 19" src="https://cloud.githubusercontent.com/assets/100664/14891447/fdf74924-0d66-11e6-82ea-6cf9283cf181.png">

Any ideas why?

Regards

**Comment by nsamuelsson** [comment]
Hallo<script>alert(123)</script>

**Comment by nsamuelsson** [comment]
Hallo <script>alert(123)</script> Welt

**Comment by ledger123** [comment]
Hi Sebastian,

I could not reproduce it on my local and then tried on our demo server and I could not reproduce it there. See AR-002 which has this description and still prints ok.

May be I have not something according to your setup?

Regards

**Comment by sweitmann** [comment]
Hi Armaghan,

I have reproduced this issue in your AR-002 transaction on app.myledger.net.  

1.) Goto 'Batch--Queue--Sales Invoice' and select the second invoice as shown here below and click on "Dowload zip file".

![bildschirmfoto 2016-06-06 um 17 31 58](https://cloud.githubusercontent.com/assets/100664/15827796/f6557d20-2c0c-11e6-8c57-1f6b4cabc792.png)

2.) Now open up the PDF in the dowloaded zip file and you will see the "'&#43;" issue there:

![bildschirmfoto 2016-06-06 um 17 38 10](https://cloud.githubusercontent.com/assets/100664/15827901/7e03a4fe-2c0d-11e6-9271-89152450d738.png)

Regards
Sebastian
