### ISSUE TITLE
Reminders do not show up in batch-queue when printed to queue

### ISSUE THREAD

**Issue by ledger123** [ledger123/runmyaccounts#63]
As reported by Sebastian,

"There is something in this commit that makes reminders printed to queue no longer visible in the report:
https://github.com/ledger123/runmyaccounts/commit/0b989966bee584c6b4cf7061ebc31371b9f0e6ee

I printed some reminders to queue and after the commit mentioned above they are no longer visible in the ‚Batch—Queue—Reminders‘ report.

When I go back to the commit before the mentioned one, they show up in the report again."

**Comment by ledger123** [comment]
This was a frustrating bug bug fixed now. :) 

This was caused by a hidden bug which got triggered by our sql-injection protection changes. It checked for blank ids as " " but with our changes blank id became "0" which was actually not blank.

Regards

**Comment by sweitmann** [comment]
Tested and delivered into Develop.

Thanks, Armaghan! You will need to close this ticket yourself, since you posted it.
