### ISSUE TITLE
DONE: Trial balance accounts are not being translated

### ISSUE THREAD

**Issue by sweitmann** [ledger123/runmyaccounts#65]
Hi Armaghan,

The chart of account translation feature ('System--Chart of Accounts--Translations') doesn't work in the Trial Balance. 

Although the account 1090 has been translated into a foreign language...

![bildschirmfoto vom 2016-06-06 10 02 24](https://cloud.githubusercontent.com/assets/100664/15815660/deee8c82-2bce-11e6-81af-615a6de309be.png)

...when I run a Trial Balance and select the foreign language...

![bildschirmfoto vom 2016-06-06 10 03 32](https://cloud.githubusercontent.com/assets/100664/15815672/f61f2d08-2bce-11e6-917a-1c7342fcec29.png)

...it still doesn't translate accordingly:

![bildschirmfoto vom 2016-06-06 10 03 50](https://cloud.githubusercontent.com/assets/100664/15815678/fe8f39a6-2bce-11e6-8d1f-009612152870.png)

Regards

**Comment by ledger123** [comment]
Hi Sebastian,
This has been fixed.

Regards

**Comment by sweitmann** [comment]
Tested. Great work, as always, thanks Armaghan! 

Regards
