### ISSUE TITLE
Errors in Tax report

### ISSUE THREAD

**Issue by sweitmann** [ledger123/runmyaccounts#68]
Hi Armaghan,

I have found this issue also exists on app.myledger.net.

1.) Goto 'System--MWST Report' (=VAT report) and click "Continue". 

2.) Take note of the total "Amount" on the accounts 2205 and 2208 shown in the summary above:

![bildschirmfoto 2016-06-06 um 18 16 45](https://cloud.githubusercontent.com/assets/100664/15829432/13d68d10-2c14-11e6-822d-d927af310233.png)

3.) Now scroll down in the detailed report and check the total on these same accounts:

a.) 
![bildschirmfoto 2016-06-06 um 18 17 31](https://cloud.githubusercontent.com/assets/100664/15829463/33cd4a5a-2c14-11e6-99fe-160ba0fae673.png)

b.) 
![bildschirmfoto 2016-06-06 um 18 18 18](https://cloud.githubusercontent.com/assets/100664/15829475/4133c2f0-2c14-11e6-8249-e22247cb12c6.png)

You will see it differs from the amounts in the summary above.

4.) Then go back one step and select "Detail" instead.

![bildschirmfoto 2016-06-06 um 18 18 49](https://cloud.githubusercontent.com/assets/100664/15829501/5d5fe472-2c14-11e6-95ab-c4899b779dc4.png)

5.) You will now find the same amount in the detailed list below as in the summary above and the reason seems to be that foreign currency invoices are counted twice.  

![bildschirmfoto 2016-06-06 um 18 20 06](https://cloud.githubusercontent.com/assets/100664/15829564/93f795c0-2c14-11e6-843f-86d151ffe424.png)

Regards

**Comment by sweitmann** [comment]
Hi Armaghan,

One more thing: Currently the 0% tax booking are also listed in the "Non-taxable" row, but it would be great if we could exclude the 0% tax bookings from the "Non-taxable" row. The "Non-taxable" row should really only contain bookings without any tax. 

![bildschirmfoto 2016-06-07 um 15 08 16](https://cloud.githubusercontent.com/assets/100664/15858902/162635f2-2cc3-11e6-8f35-a6933d9a863c.png)

![bildschirmfoto 2016-06-07 um 15 12 30](https://cloud.githubusercontent.com/assets/100664/15858911/1f89f3cc-2cc3-11e6-8f95-e386318c40fe.png)

![bildschirmfoto 2016-06-07 um 15 20 49](https://cloud.githubusercontent.com/assets/100664/15858996/79bd6496-2cc3-11e6-9493-4a754f572857.png)

Regards

**Comment by sweitmann** [comment]
Hi Armaghan,

one more thing: if you book a zero tax transaction (AR/AP) by marking the zero tax check-box, subsequently when you look at the booking in 'General Ledger--Reports--Journal' you will find that the zero tax account is listed correctly. 

But if you open the booking itself there is nothing to show the zero tax booking, since the zero tax check-box is no longer marked.

When you book it, you see the zero tax booking because of the marked check-box:

![bildschirmfoto 2016-07-08 um 08 53 25](https://cloud.githubusercontent.com/assets/100664/16679677/a97d098c-44e9-11e6-9deb-929d6ee8da43.png)

But when you open it again, there is nothing to tell you that there is a zero tax booking involved, because the check-box is no longer marked:

![bildschirmfoto 2016-07-08 um 08 54 06](https://cloud.githubusercontent.com/assets/100664/16679692/cb2247d2-44e9-11e6-8664-ecbddebc1a3b.png)

Regards

**Comment by ledger123** [comment]
Hi Sebastian,

As was discussed we shall replace this existing report with new report we had starting building for rel3. I have copied the code for that report and made it work here. It is 'System--New MWST Report' in menu.

Now I will be working to make it work as intended. Nothing to do at your side yet on this issue.

Regards

**Comment by sweitmann** [comment]
Hi Armaghan,

I will be posting the issues I find here as I become aware of them. Then we can discuss them on Monday next week, before starting the new session.

- Foreign currency transactions work for invoices, but not for transactions. AR and AP transactions show correct amount for "Amount", but for some reason shows doubled amount for "tax". Checkout "Line Tax 012" AR and AP booking.

- AP tax bookings are sometimes marked with * and sometimes not. Checkout Line Tax 009 and Line Tax 011a.

Regards

**Comment by sweitmann** [comment]
Hi Armaghan, 

tested and all works really well. I'm so impressed by your great work and how you have helped me to create this new line tax report. We only have one last minor issue left.

As you can see in the database I sent you over slack on April 27th, before I update the database for this fix, trans_id 14069 looks like this:
![bildschirmfoto 2017-05-03 um 11 54 59](https://cloud.githubusercontent.com/assets/100664/25905301/f37266be-35a1-11e7-86cf-ee8ffbf46c3d.png)
As you can see by the chart_id and amount it has two tax amounts that neutralize each other. 

After I update the database by running the sql-scripts this same transaction looks like this:
![bildschirmfoto 2017-05-03 um 11 55 26](https://cloud.githubusercontent.com/assets/100664/25905444/5ae39a2a-35a2-11e7-9a00-2dda6820fcd0.png)

But it should look like this:
![bildschirmfoto 2017-05-03 um 11 58 30](https://cloud.githubusercontent.com/assets/100664/25905514/82ce3d9c-35a2-11e7-98f4-d8353c537206.png)

Do you think you can adjust the sql-script a little, so that it gets these last numbers right?

Regards

**Comment by sweitmann** [comment]
Thanks, Armaghan! The new Line Tax Report is perfect. Closing this ticket now.

**Comment by sweitmann** [comment]
As discussed on Slack:

The following transaction, wich was booked in earlier version and has also not been re-posted in current version, contains an error in the taxamount field in acc_trans.

![bildschirmfoto 2017-09-18 um 14 46 08](https://user-images.githubusercontent.com/100664/30542826-15a42b00-9c81-11e7-8f30-0a09604b4e44.png)


This error is not corrected during ‘System--Line Tax Report Fix’ and the transaction doesn’t show up in Ledger Doctor either.

It would be great if it would appear in Ledger Doctor or be corrected during 'System--Line Tax Report Fix'.

Regards

**Comment by sweitmann** [comment]
Released into develop. Thanks, Armaghan! Closing this ticket now.
