### ISSUE TITLE
Add certain invoice variables to reminders templates

### ISSUE THREAD

**Issue by sweitmann** [ledger123/runmyaccounts#69]
Hi Armaghan,

it would be great if we could add some of the AR Sales Invoice template variables to the reminders module, so that these can also be used in the first, second and third level reminder templates. 

To start with we would need the following invoice variables to be accessible in these 3 reminders templates:

a.) Shipping Address detail variables

![bildschirmfoto 2016-06-07 um 09 36 17](https://cloud.githubusercontent.com/assets/100664/15849546/709d56a8-2c93-11e6-838c-a6749bb9c9d4.png)

b.) AR Sales invoice "Shipping Point", "Ship via" and "Waybill" variables

![bildschirmfoto 2016-06-07 um 09 36 55](https://cloud.githubusercontent.com/assets/100664/15849565/803518c6-2c93-11e6-9007-ba420921b77e.png)

c.) And the Sales Invoice "Description" variable

![bildschirmfoto 2016-06-07 um 09 36 42](https://cloud.githubusercontent.com/assets/100664/15849600/ae97cec0-2c93-11e6-96a3-b57831863bbb.png)

Regards

**Comment by ledger123** [comment]
Hi Sebastian,
I have tested and confirmed that these variables are already available in reminder templates.
  shiptoname
  shiptoaddress1
  shiptoaddress2
  shiptocity
  shiptostate
  shiptozipcode
  shiptocountry
  shiptocontact
  shiptophone
  shiptofax
  shiptoemail

Invoice description is also available as 'invdescription'

I have added following new variables.
  shippingpoint
  shipvia
  waybill

Regards

**Comment by sweitmann** [comment]
Hi Armaghan, 

we need to adjust one more thing. The idea is to make the shipto variables work the same in the reminders templates as in the invoice templates. 

Currently, the following LaTeX code in the invoice template:

![bildschirmfoto 2016-06-08 um 16 15 03](https://cloud.githubusercontent.com/assets/100664/15897509/fef615aa-2d94-11e6-97d5-93ca9782d718.png)

a.) Will print the shipto address if the invoice contains one

b.) else it will print the "standard" address instead.

When we use the same LaTeX code in the reminder template it

a.) Will print the shipto address if the invoice contains one

b.) else it will print nothing.

It would be great if this LaTeX code produced the same result in both invoice and reminder. And the preferred version is that it should always print "normal" address if there is no shipto address in the invoice.

Regards

**Comment by sweitmann** [comment]
Released into develop. Thanks, Armaghan.
