### ISSUE TITLE
Quotes around the text in CSV export file

### ISSUE THREAD

**Issue by sweitmann** [ledger123/runmyaccounts#70]
Hi Armaghan, 

today when we export transactions by clicking on „CSV“ under ‚General Ledger—Reports—Journal‘ the columns are separated by a , (comma). Sometimes a company name contains a , (comma) and this then leads to errors in the column entry separation.

![bildschirmfoto 2016-06-08 um 11 47 07](https://cloud.githubusercontent.com/assets/100664/15890594/a6027db8-2d70-11e6-80d0-df88a8b01236.png)

![bildschirmfoto 2016-06-08 um 12 01 16](https://cloud.githubusercontent.com/assets/100664/15890623/c9e2c27e-2d70-11e6-8c0a-bcda866fbf04.png)

Your suggestion to solve this issue was to "put quotes around the text". Sounds perfect, so here is the ticket for doing exactly that, thanks.

Regards

**Comment by ledger123** [comment]
Hi Sebastian,

This is done and pushed to github on its own branch.

Regards

**Comment by sweitmann** [comment]
Tested. Solved. Closing this ticket now. Thanks, Armaghan.
