### ISSUE TITLE
Date validation for 'System--Audit Control'

### ISSUE THREAD

**Issue by sweitmann** [ledger123/runmyaccounts#72]
Hi Armaghan,

can we add some kind of date validation for 'System-Audit Control' to check that the date is entered according to the users 'Preferences'?

![bildschirmfoto 2016-07-08 um 12 20 33](https://cloud.githubusercontent.com/assets/100664/16684665/9f0349b8-4506-11e6-82db-3cc95512fd5d.png)

![bildschirmfoto 2016-07-08 um 12 20 59](https://cloud.githubusercontent.com/assets/100664/16684668/a1e7db80-4506-11e6-8ad9-b915e74ee54f.png)

Regards

**Comment by ledger123** [comment]
Hi Sebastian,

This is fixed and code pushed.

Regards
