### ISSUE TITLE
Project Transaction Report does not consider exchange rate difference

### ISSUE THREAD

**Issue by sweitmann** [ledger123/runmyaccounts#77]
Hi Armaghan,

The two reports 'Projects--Reports--Transactions' and 'Projects--Reports--Summary' show different results for the same project, because the first doesn't consider exchange rate differences.

a.) 'Projects--Reports--Transactions'
![bildschirmfoto 2016-08-03 um 17 31 39](https://cloud.githubusercontent.com/assets/100664/17371566/a109d264-59a0-11e6-8fe2-9216590d7d1e.png)

b.) 'Projects--Reports--Summary'
![bildschirmfoto 2016-08-03 um 17 31 54](https://cloud.githubusercontent.com/assets/100664/17371588/b1f99938-59a0-11e6-9785-3ba49611e1a8.png)

Regards

**Comment by ledger123** [comment]
Hi Sebastian,

This is also fixed and code pushed.

Regards

**Comment by sweitmann** [comment]
Hi Armaghan,

I'm still having an issue with this one on my local server. Can you please switch app.myledger to 077_project_trans_does_not_consider_fx_diff branch and give me a sign, so that I can test it and show you my issue on app.myledger? Thanks.

Regards

**Comment by ledger123** [comment]
Hi Sebastian,

I have switched to 077_project_trans_does_not_consider_fx_diff branch.

Regards

**Comment by sweitmann** [comment]
Hi Armaghan,

thanks, I have done some testing on the app.myledger server and 'Projects--Reports--Summary' now considers fx diff and thus shows the correct results:

![bildschirmfoto vom 2016-09-22 09 47 26](https://cloud.githubusercontent.com/assets/100664/18740457/175e6454-80aa-11e6-9588-e6194d5dd988.png)

Only when you click on the project number in the project summary view above and scroll down into the transactions view, it continues to show you the single transactions without considering the fx diff:

![bildschirmfoto vom 2016-09-22 09 48 45](https://cloud.githubusercontent.com/assets/100664/18740468/24e40b10-80aa-11e6-8862-1305c8bfb5ea.png)

But if you click directly on 'Projects--Reports--Transactions', it does consider the fx diff and thus shows correct results:

![bildschirmfoto vom 2016-09-22 09 52 02](https://cloud.githubusercontent.com/assets/100664/18740489/3f3396e8-80aa-11e6-8b87-c199676150c0.png)

Not sure how to make it happen, but if the scroll down from 'Projects--Reports--Summary' would link to 'Projects-Reports-Transactions' report instead, this issue would be solved. 

Regards

**Comment by sweitmann** [comment]
'System--Projekt Erfolgsrechnung' can display Income Statement for all different projects. In order to check the correctness of the report, it would be great if there would also be a checkbox for "Other non-project bookings". 

That way the totals in this report could simply be validated against standard Income Statement for confirmation.

Regards
