### ISSUE TITLE
Internal Notes not re-loaded

### ISSUE THREAD

**Issue by sweitmann** [ledger123/runmyaccounts#78]
Hi Armaghan,

On our app.myledger server I have entered two different notes for two different the customers. 

![bildschirmfoto 2016-08-05 um 12 51 16](https://cloud.githubusercontent.com/assets/100664/17434670/0d357c4c-5b0c-11e6-813f-d04a60516332.png)

When I go to 'AR--Sales Invoice' and select the first customer I can see the related internal notes in the appropriate box. 

![bildschirmfoto 2016-08-05 um 12 52 32](https://cloud.githubusercontent.com/assets/100664/17434841/08b0abe6-5b0d-11e6-9ea7-e519aafa97d4.png)
 
But when I change the customer the internal notes don't re-load and thus the internal notes of the previous selected customer remain.

![bildschirmfoto 2016-08-05 um 12 53 04](https://cloud.githubusercontent.com/assets/100664/17434869/3dd77598-5b0d-11e6-90f4-21593a5a9ac9.png)

Regards

**Comment by ledger123** [comment]
Hi Sebastian,

This is fixed and code pushed.

Regards

**Comment by sweitmann** [comment]
Hi Armaghan,

Tested and confirmed. Perfect, thanks for this swift fix. Please merge into develop and give me a sign when done.

Closing this ticket now.

Regards

**Comment by ledger123** [comment]
Hi Sebastian,

This fix has been merged to rel4 branch. Have a look.

Regards
