### ISSUE TITLE
TESTING: Incorrect price from price matrix when using foreign currency

### ISSUE THREAD

**Issue by ledger123** [ledger123/runmyaccounts#80]
Hi Sebastian,

As reported by you this bug seems to be triggered in a very special case due to ordering of SELECT rows by database in a particular way.

I am posting a fix following this ticket on this ticket branch to do your testing.

Regards

**Comment by sweitmann** [comment]
Tested and released on the 30th August 2016. Since you opened this ticket; could you please remove TESTING from header and close this ticket when you have a minute. Thanks, Armaghan!
