### ISSUE TITLE
ZUGFeRD

### ISSUE THREAD

**Issue by sweitmann** [ledger123/runmyaccounts#87]
Hi Armaghan,

in order to enable small and medium-sized enterprises to benefit from the advantages of e-invoicing and thus help them make their accounting transactions easier and faster to handle, we have started a project to include the Sales Invoice data from invoices created in SQL-Leder in an .xml file that would be attached to the PDF created with LaTeX (PDF/A). The concept is based on the new ZUGFeRD standard for electronic invoices which is currently gaining ground in Europe. 

You will find some more detailed information on ZUGFeRD here:
http://www.pdfunit.com/en/documentation/java/testscope/zugferd.html

We have done some testing and found that SQL-Ledger/LaTeX can already almost do this with the aid of some LaTeX plugins (\usepackage{embedfile}
\usepackage{filecontents}, but unfortunately there are still some small things missing in SQL-Ledger to make it work:

1.) We need a new variable in the Sales Invoice LaTeX template with the Invoice Date and Due Date in the following strict format "YYYYMMDD", no matter what the date format has been set to in the 'Prefereces' settings;

2.) We need a new variable in the Sales Invoice LaTeX template with the total sum of all taxes <%totaltax%>;

3.) And we also need to have more detailed variables for the Default Company Address:

![bildschirmfoto vom 2016-09-22 10 45 40](https://cloud.githubusercontent.com/assets/100664/18741881/bd995624-80b1-11e6-9205-5e8bf261f5db.png)

The best would be if the Default Company Address could be as detailed as the standard customer and vendor address information:

![bildschirmfoto vom 2016-09-22 10 47 58](https://cloud.githubusercontent.com/assets/100664/18741945/0b5cc5c6-80b2-11e6-9b77-f68af460f97a.png)

Regards

**Comment by ledger123** [comment]
Hi Sebastian,

<%totaltax% variable is already there.

I have added following new variables:

<%invdate2%>
<%duedate2%>
<%companyaddress1%>
<%companyaddress2%>
<%companycity%>
<%companystate%>
<%companyzip%>
<%companycountry%>

For company variables you just need to add address information in defaults in the format shown in the attached image. I have not added seperate columns as you had suggested but if you think that will be better than the solution I have implemented then I shall do that.

Regards

**Comment by ledger123** [comment]
And here goes the image to show how to add address for above variables.

Regards
![address](https://cloud.githubusercontent.com/assets/13597/18945049/0a346718-8642-11e6-927b-db100a1a5b15.png)

**Comment by sweitmann** [comment]
Hi Armaghan, tested and everything looks great. Thanks. Please feel free to merge into develop.

Regards

**Comment by sweitmann** [comment]
Hi Armaghan, 

as discussed, we would need the following variables for the xml file:

<%xml_invdate%> (will replace <%invdate2%> which can be removed) 
<%xml_duedate%> (will replace <%duedate2%> which can be removed) 
<%xml_tax%> 
<%xml_taxbase%> 
<%xml_taxrate%> 
<%xml_taxbaseinclusive%> 
<%xml_subtotal%> 
<%xml_totaltax%> 
<%xml_qty%> 
<%xml_linetotal%> 
<%xml_sumcarriedforward%> 
<%xml_deliverydate%> 
<%xml_sellprice%> 
<%xml_invtotal%> 
<%xml_total%> 
<%xml_paid%>

Regards

**Comment by ledger123** [comment]
Hi Sebastian,

I have pushed the code in 087_ZUGFeRD branch with the required changes.

Variables needs to be tested in the particular template. Please let me know if there any adjustments to be made.

Regards

**Comment by sweitmann** [comment]
Hi Armaghan, 

This code has been tested and it looks good. Thank you! 

Only one more minor thing. Could you please add four decimal places to <%xml_qty%>?

![das_zugferd-format_1p0_pdf__seite_50_von_132_](https://cloud.githubusercontent.com/assets/100664/20598213/50113324-b248-11e6-9805-f08ad3e8bdfc.png)

Regards

**Comment by ledger123** [comment]
Hi Sebastian,

Added 4 decimals to xml_qty and pushed to github.

Regards

**Comment by sweitmann** [comment]
Hi Armaghan, 

Tested. Beautiful. Looks great. Thanks! Please release into develop whenever convenient.

Regards

**Comment by ledger123** [comment]
Hi Sebastian,

Merged and updated release date.

Regards
