### ISSUE TITLE
Two empty rows in foreign currency transactions

### ISSUE THREAD

**Issue by sweitmann** [ledger123/runmyaccounts#88]
Hi Armaghan, 

When posting AR and AP transactions in foreign currency, we now always get two extra empty rows:

![bildschirmfoto 2016-10-04 um 11 34 21](https://cloud.githubusercontent.com/assets/100664/19069515/96d05446-8a27-11e6-8452-151399453f74.png)

Any ideas?

Regards

**Comment by ledger123** [comment]
Hi Sebastian,

I have created a new branch 088_ for this issue and added code to view acc_trans rows in the footer.



Could you kindly help me finding some pattern of unwanted and wanted blank rows. This will make it easy to adjust code to remove unwanted blank lines.

Regards

**Comment by ledger123** [comment]
Here is how the footer of any transaction will look like

![blankrows](https://cloud.githubusercontent.com/assets/13597/20136220/7438882e-a695-11e6-9e88-5a81667dabc7.png)

**Comment by sweitmann** [comment]
Hi Armaghan,

found it! This commit causes the problem: 

https://github.com/ledger123/runmyaccounts/commit/e561c4803f5ab8496271df817d61a7965ba0884e

Regards

**Comment by ledger123** [comment]
Hi Sebastian,

Fixed the issue and pushed code to github.

Regards

**Comment by ledger123** [comment]
Also following queries can take care of existing blank rows:
These will show:

    SELECT * FROM acc_trans WHERE amount = 0 AND chart_id IN (SELECT id FROM chart WHERE link = 'AR');
    SELECT * FROM acc_trans WHERE amount = 0 AND chart_id IN (SELECT fldvalue::integer FROM defaults WHERE fldname IN ('fxgain_accno_id', 'fxloss_accno_id'));

These queries will delete

    DELETE FROM acc_trans WHERE amount = 0 AND chart_id IN (SELECT id FROM chart WHERE link = 'AR');
    DELETE FROM acc_trans WHERE amount = 0 AND chart_id IN (SELECT fldvalue::integer FROM defaults WHERE fldname IN ('fxgain_accno_id', 'fxloss_accno_id'));

Regards

**Comment by sweitmann** [comment]
Hi Armaghan,

tested. Looks great. Thanks! Please release into develop whenever convenient. 

Regards
