### ISSUE TITLE
duplicate entries in menu.ini

### ISSUE THREAD

**Issue by sn0wman2** [ledger123/runmyaccounts#94]
Since the last commit of the file menu.ini, there are many duplicate entries.

**Comment by sweitmann** [comment]
Hi Peter,
 
thanks for your input! Could you please be more specific? Which version, branch and exact commit are you referring to? And please feel free to add some screenshots, they are usually very helpful too. 

Regards

**Comment by sn0wman2** [comment]
Hi Sebastian
I'm referring to the commit ee358ba481a10da3fd0eb2c2589642b54c57e323. For example "[AR--Add Transaction]" is now duplicated in menu.ini.

**Comment by sweitmann** [comment]
Thanks, Peter. I will look into it and get back to you. 

Regards

**Comment by sweitmann** [comment]
Hi Peter, 

Nils has removed the duplicate entries in the develop branch and this commit will be merged into master ahead of the next release:

https://github.com/ledger123/runmyaccounts/blob/develop/menu.ini

Thank you for your imput. Would you please close this ticket now?

Regards

**Comment by sweitmann** [comment]
Hi Peter, 

Can you please close this ticket? Since you are the owner, you are the only one who can close it.

Regards
