### ISSUE TITLE
Income Statement Departments report as CSV-export

### ISSUE THREAD

**Issue by sweitmann** [ledger123/runmyaccounts#98]
Hi Armghan, 

Today we have the 'System--Income Statement Departments' report that shows the department column by column, like this:
![bildschirmfoto 2016-12-01 um 17 06 53](https://cloud.githubusercontent.com/assets/100664/20801568/b1bcc25e-b7e9-11e6-8026-c697076ca002.png)

Can you please help us to add a CSV-export feature for that report that delivers the same data on a row by row level instead, like this?

![bildschirmfoto 2016-12-01 um 17 12 18](https://cloud.githubusercontent.com/assets/100664/20801652/e3113268-b7e9-11e6-9c00-1e5d4560417e.png)

Regards

**Comment by ledger123** [comment]
Hi Sebastian,

This is added. You just need to check 'CSV' button before clicking Continue.

Please let me know any adjustments if any.

Regards

**Comment by ledger123** [comment]
Hi Sebastian,

This is done for project income statement too and code is pushed and merged into develop.

Regards

**Comment by sweitmann** [comment]
Thanks, Armaghan! Closing this ticket now.
