### ISSUE TITLE
Mysql support

### ISSUE THREAD

**Issue by olimination** [ledger123/runmyaccounts#99]
I just wonder if there is a plan for supporting other databases like Mysql/MariaDB?
What would be needed to support also other databases? Is _ledger123/runmyaccounts_ web app tightly coupled to the Postgres DB?

Thanks for info.

**Comment by sweitmann** [comment]
Hi Oliver,

Currently we don't have any plans to run the ledger123/runmyaccouts SQL-Ledger version on any other databases than PostgreSQL.

May I ask why you prefer not to run it on PostgreSQL?

Regards

**Comment by olimination** [comment]
It is just an infrastructure limitation because Postgres is not supported on my hosting.

Thanks for feedback.
